# Generated by Django 5.2.4 on 2025-07-30 10:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='ชื่อเอกสาร')),
                ('description', models.TextField(blank=True, null=True, verbose_name='คำอธิบาย')),
                ('file', models.FileField(upload_to='technical_docs/', verbose_name='ไฟล์เอกสาร')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='วันที่สร้าง')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไข')),
            ],
            options={
                'verbose_name': 'เอกสารเทคนิค',
                'verbose_name_plural': 'เอกสารเทคนิค',
                'ordering': ['-created_at'],
            },
        ),
    ]
