# Generated by Django 5.2.4 on 2025-08-03 11:24

import technical_docs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical_docs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicaldocument',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, verbose_name='ชื่อไฟล์ต้นฉบับ'),
        ),
        migrations.AlterField(
            model_name='technicaldocument',
            name='file',
            field=models.FileField(upload_to=technical_docs.models.get_upload_path, verbose_name='ไฟล์เอกสาร'),
        ),
    ]
