# Generated by Django 5.2.4 on 2025-07-12 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organize', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organize',
            options={'verbose_name': 'หน่วยงาน', 'verbose_name_plural': 'หน่วยงาน'},
        ),
        migrations.AlterField(
            model_name='organize',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='ที่อยู่'),
        ),
        migrations.AlterField(
            model_name='organize',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง'),
        ),
        migrations.AlterField(
            model_name='organize',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='อีเมล'),
        ),
        migrations.AlterField(
            model_name='organize',
            name='name',
            field=models.CharField(max_length=100, verbose_name='ชื่อหน่วยงาน'),
        ),
        migrations.AlterField(
            model_name='organize',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='เบอร์โทรศัพท์'),
        ),
        migrations.AlterField(
            model_name='organize',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไขล่าสุด'),
        ),
    ]
