# Generated by Django 5.2.4 on 2025-07-30 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organize', '0002_alter_organize_options_alter_organize_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organize',
            options={'ordering': ['name'], 'verbose_name': 'หน่วยงาน', 'verbose_name_plural': 'หน่วยงาน'},
        ),
        migrations.AddField(
            model_name='organize',
            name='is_main_unit',
            field=models.BooleanField(default=False, verbose_name='เป็นหน่วยงานหลัก'),
        ),
        migrations.AddField(
            model_name='organize',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organize.organize', verbose_name='หน่วยงานหลัก'),
        ),
        migrations.AddField(
            model_name='organize',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='organizations', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ใช้งาน'),
        ),
    ]
