# Generated by Django 5.2.4 on 2025-09-24 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employee_options_alter_employee_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'ผู้ใช้งาน', 'verbose_name_plural': 'ผู้ใช้งาน'},
        ),
    ]
