# Generated by Django 5.2.4 on 2025-08-03 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ชื่อ widget')),
                ('widget_type', models.CharField(choices=[('chart', 'กราฟ'), ('table', 'ตาราง'), ('metric', 'ตัวชี้วัด'), ('list', 'รายการ')], max_length=50, verbose_name='ประเภท widget')),
                ('data_source', models.CharField(max_length=100, verbose_name='แหล่งข้อมูล')),
                ('position', models.IntegerField(default=0, verbose_name='ตำแหน่ง')),
                ('is_active', models.BooleanField(default=True, verbose_name='ใช้งาน')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
            ],
            options={
                'verbose_name': 'Widget แดชบอร์ด',
                'verbose_name_plural': 'Widget แดชบอร์ด',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ชื่อเทมเพลต')),
                ('description', models.TextField(blank=True, verbose_name='คำอธิบาย')),
                ('template_type', models.CharField(choices=[('calibration', 'รายงานการสอบเทียบ'), ('machine', 'รายงานเครื่องมือ'), ('employee', 'รายงานพนักงาน'), ('organization', 'รายงานหน่วยงาน'), ('summary', 'รายงานสรุป')], max_length=50, verbose_name='ประเภทเทมเพลต')),
                ('is_active', models.BooleanField(default=True, verbose_name='ใช้งาน')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไข')),
            ],
            options={
                'verbose_name': 'เทมเพลตรายงาน',
                'verbose_name_plural': 'เทมเพลตรายงาน',
            },
        ),
        migrations.CreateModel(
            name='ReportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(max_length=50, verbose_name='ประเภทรายงาน')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('file_path', models.CharField(blank=True, max_length=500, verbose_name='เส้นทางไฟล์')),
                ('file_size', models.IntegerField(default=0, verbose_name='ขนาดไฟล์ (bytes)')),
                ('status', models.CharField(choices=[('success', 'สำเร็จ'), ('failed', 'ล้มเหลว'), ('processing', 'กำลังประมวลผล')], default='processing', max_length=20, verbose_name='สถานะ')),
                ('error_message', models.TextField(blank=True, verbose_name='ข้อความผิดพลาด')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='สร้างโดย')),
            ],
            options={
                'verbose_name': 'บันทึกรายงาน',
                'verbose_name_plural': 'บันทึกรายงาน',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ชื่อกำหนดการ')),
                ('frequency', models.CharField(choices=[('daily', 'รายวัน'), ('weekly', 'รายสัปดาห์'), ('monthly', 'รายเดือน'), ('quarterly', 'ราย 3 เดือน'), ('yearly', 'รายปี')], max_length=20, verbose_name='ความถี่')),
                ('recipients', models.TextField(verbose_name='ผู้รับรายงาน (อีเมล)')),
                ('is_active', models.BooleanField(default=True, verbose_name='ใช้งาน')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='รันครั้งล่าสุด')),
                ('next_run', models.DateTimeField(blank=True, null=True, verbose_name='รันครั้งถัดไป')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.reporttemplate', verbose_name='เทมเพลต')),
            ],
            options={
                'verbose_name': 'กำหนดการรายงาน',
                'verbose_name_plural': 'กำหนดการรายงาน',
            },
        ),
    ]
