# Generated by Django 5.2.4 on 2025-07-30 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('organize', '0003_alter_organize_options_organize_is_main_unit_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username'], 'verbose_name': 'ผู้ใช้งาน', 'verbose_name_plural': 'ผู้ใช้งาน'},
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='วันที่สร้าง'),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ชื่อ (อังกฤษ)'),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name_th',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ชื่อ (ไทย)'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='นามสกุล (อังกฤษ)'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name_th',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='นามสกุล (ไทย)'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_extension',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='เบอร์โทรศัพท์ 5 หลัก'),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='วันที่แก้ไข'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='อีเมล'),
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ระดับ'),
        ),
        migrations.AlterField(
            model_name='user',
            name='organize',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organize.organize', verbose_name='หน่วยงาน'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='เบอร์โทรศัพท์'),
        ),
        migrations.AlterField(
            model_name='user',
            name='prefix',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='คำนำหน้า'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, verbose_name='ชื่อผู้ใช้'),
        ),
    ]
