# Generated by Django 5.2.4 on 2025-10-03 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_user_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('unit_user', 'หน่วยผู้ใช้'), ('admin', 'ผู้ดูแลระบบ'), ('technician', 'ช่างเทคนิค'), ('viewer', 'ผู้ดูข้อมูล')], max_length=50, unique=True, verbose_name='ชื่อบทบาท')),
                ('description', models.TextField(blank=True, verbose_name='คำอธิบาย')),
                ('can_view_machine', models.BooleanField(default=True, verbose_name='ดูข้อมูลเครื่องมือ')),
                ('can_add_machine', models.BooleanField(default=False, verbose_name='เพิ่มเครื่องมือ')),
                ('can_edit_machine', models.BooleanField(default=False, verbose_name='แก้ไขเครื่องมือ')),
                ('can_delete_machine', models.BooleanField(default=False, verbose_name='ลบเครื่องมือ')),
                ('can_send_notification', models.BooleanField(default=False, verbose_name='ส่งแจ้งเตือน')),
                ('can_view_calibration', models.BooleanField(default=True, verbose_name='ดูข้อมูลสอบเทียบ')),
                ('can_add_calibration', models.BooleanField(default=False, verbose_name='เพิ่มข้อมูลสอบเทียบ')),
                ('can_edit_calibration', models.BooleanField(default=False, verbose_name='แก้ไขข้อมูลสอบเทียบ')),
                ('can_delete_calibration', models.BooleanField(default=False, verbose_name='ลบข้อมูลสอบเทียบ')),
                ('can_view_organization', models.BooleanField(default=False, verbose_name='ดูข้อมูลหน่วยงาน')),
                ('can_manage_organization', models.BooleanField(default=False, verbose_name='จัดการหน่วยงาน')),
                ('can_view_users', models.BooleanField(default=False, verbose_name='ดูข้อมูลผู้ใช้')),
                ('can_manage_users', models.BooleanField(default=False, verbose_name='จัดการผู้ใช้')),
                ('can_view_equipment', models.BooleanField(default=False, verbose_name='ดูเครื่องมือสอบเทียบ')),
                ('can_manage_equipment', models.BooleanField(default=False, verbose_name='จัดการเครื่องมือสอบเทียบ')),
                ('can_view_technical_docs', models.BooleanField(default=False, verbose_name='ดูเอกสารเทคนิค')),
                ('can_manage_technical_docs', models.BooleanField(default=False, verbose_name='จัดการเอกสารเทคนิค')),
                ('can_view_reports', models.BooleanField(default=True, verbose_name='ดูรายงาน')),
                ('can_export_reports', models.BooleanField(default=True, verbose_name='ส่งออกรายงาน')),
                ('can_edit_reports', models.BooleanField(default=False, verbose_name='แก้ไขรายงาน')),
                ('can_download_certificates', models.BooleanField(default=False, verbose_name='ดาวน์โหลดใบรับรอง')),
                ('can_access_admin', models.BooleanField(default=False, verbose_name='เข้าถึงหลังบ้าน')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไข')),
            ],
            options={
                'verbose_name': 'บทบาทผู้ใช้',
                'verbose_name_plural': 'บทบาทผู้ใช้',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='user_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.userrole', verbose_name='บทบาทผู้ใช้'),
        ),
    ]
