# Generated by Django 5.2.4 on 2025-10-03 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userrole_user_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='can_change_priority',
            field=models.BooleanField(default=False, verbose_name='เปลี่ยนระดับความเร่งด่วน'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='can_close_work',
            field=models.BooleanField(default=False, verbose_name='ปิดงาน'),
        ),
    ]
