# Generated by Django 5.2.4 on 2025-10-03 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userrole_can_change_priority_userrole_can_close_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='name',
            field=models.CharField(choices=[('unit_user', 'หน่วยผู้ใช้'), ('admin', 'ผู้ดูแลระบบ'), ('technician', 'ช่างเทคนิค'), ('coordinator', 'เจ้าหน้าที่แผนกจัดดำเนินงาน'), ('viewer', 'ผู้ดูข้อมูล')], max_length=50, unique=True, verbose_name='ชื่อบทบาท'),
        ),
    ]
