# Generated by Django 5.2.4 on 2025-07-12 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MachineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MachineUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organize_id', models.IntegerField()),
                ('name', models.CharField(max_length=45)),
                ('model', models.CharField(blank=True, max_length=45, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=20, null=True)),
                ('range', models.CharField(blank=True, max_length=10, null=True)),
                ('res_uuc', models.CharField(blank=True, max_length=5, null=True)),
                ('update', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('machine_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine.machinetype')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine.machineunit')),
                ('manufacture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine.manufacture')),
            ],
        ),
    ]
