# Generated by Django 5.2.4 on 2025-07-12 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machine',
            options={'verbose_name': 'เครื่องมือ', 'verbose_name_plural': 'เครื่องมือ'},
        ),
        migrations.AlterModelOptions(
            name='machinetype',
            options={'verbose_name': 'ประเภทเครื่องมือ', 'verbose_name_plural': 'ประเภทเครื่องมือ'},
        ),
        migrations.AlterModelOptions(
            name='machineunit',
            options={'verbose_name': 'หน่วยนับ', 'verbose_name_plural': 'หน่วยนับ'},
        ),
        migrations.AlterModelOptions(
            name='manufacture',
            options={'verbose_name': 'ผู้ผลิต', 'verbose_name_plural': 'ผู้ผลิต'},
        ),
        migrations.AlterField(
            model_name='machine',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='ลบแล้ว'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine.machinetype', verbose_name='ประเภทเครื่องมือ'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='manufacture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine.manufacture', verbose_name='ผู้ผลิต'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='model',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='รุ่น'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='name',
            field=models.CharField(max_length=45, verbose_name='ชื่อเครื่องมือ'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='organize_id',
            field=models.IntegerField(verbose_name='รหัสหน่วยงาน'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='range',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ช่วงการวัด'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='res_uuc',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='ความละเอียด UUC'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='serial_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='หมายเลขเครื่อง'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine.machineunit', verbose_name='หน่วยนับ'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='วันที่อัปเดต'),
        ),
        migrations.AlterField(
            model_name='machinetype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='ประเภทเครื่องมือ'),
        ),
        migrations.AlterField(
            model_name='machineunit',
            name='name',
            field=models.CharField(max_length=100, verbose_name='หน่วยนับ'),
        ),
        migrations.AlterField(
            model_name='manufacture',
            name='name',
            field=models.CharField(max_length=100, verbose_name='ผู้ผลิต'),
        ),
    ]
