# Generated by Django 5.2.4 on 2025-07-30 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert', '0002_alter_certificate_options_alter_certificate_cert_no_and_more'),
        ('machine', '0002_alter_machine_options_alter_machinetype_options_and_more'),
        ('organize', '0003_alter_organize_options_organize_is_main_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='organize_id',
        ),
        migrations.AddField(
            model_name='machine',
            name='organize',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organize.organize', verbose_name='หน่วยงาน'),
        ),
        migrations.CreateModel(
            name='CalibrationEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ชื่อเครื่องมือวัดใช้สอบเทียบ')),
                ('model', models.CharField(blank=True, max_length=100, null=True, verbose_name='รุ่น')),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='หมายเลขเครื่อง')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไข')),
                ('certificate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cert.certificate', verbose_name='ใบรับรอง')),
                ('machine_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine.machinetype', verbose_name='ประเภท')),
            ],
            options={
                'verbose_name': 'เครื่องมือที่ใช้สอบเทียบ',
                'verbose_name_plural': 'เครื่องมือที่ใช้สอบเทียบ',
            },
        ),
        migrations.AddField(
            model_name='machine',
            name='calibration_equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='machine.calibrationequipment', verbose_name='เครื่องมือที่ใช้สอบเทียบ'),
        ),
    ]
