# Generated by Django 5.2.4 on 2025-08-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0004_machine_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibrationequipment',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='วันที่สร้าง'),
        ),
    ]
