# Generated by Django 5.2.4 on 2025-08-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0005_alter_calibrationequipment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibrationequipment',
            name='certificate',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ใบรับรอง'),
        ),
    ]
