# Generated by Django 5.2.4 on 2025-09-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0006_alter_calibrationequipment_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='customer_asset_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='รหัสลูกค้า/ทรัพย์สิน'),
        ),
        migrations.AddField(
            model_name='machine',
            name='option',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ตัวเลือกเพิ่มเติม'),
        ),
    ]
