# Generated by Django 5.2.4 on 2025-07-12 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert', '0001_initial'),
        ('machine', '0002_alter_machine_options_alter_machinetype_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'verbose_name': 'ใบรับรองการสอบเทียบ', 'verbose_name_plural': 'ใบรับรองการสอบเทียบ'},
        ),
        migrations.AlterField(
            model_name='certificate',
            name='cert_no',
            field=models.CharField(max_length=50, unique=True, verbose_name='เลขที่ใบรับรอง'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='expire_date',
            field=models.DateField(blank=True, null=True, verbose_name='วันหมดอายุ'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='certificates/', verbose_name='ไฟล์ใบรับรอง'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='issue_date',
            field=models.DateField(verbose_name='วันที่ออกใบรับรอง'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine.machine', verbose_name='เครื่องมือ'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='หมายเหตุ'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไขล่าสุด'),
        ),
    ]
