# Generated by Django 5.2.4 on 2025-07-12 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('std', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='standard',
            options={'verbose_name': 'มาตรฐาน', 'verbose_name_plural': 'มาตรฐาน'},
        ),
        migrations.AlterField(
            model_name='standard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง'),
        ),
        migrations.AlterField(
            model_name='standard',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='รายละเอียด'),
        ),
        migrations.AlterField(
            model_name='standard',
            name='name',
            field=models.CharField(max_length=100, verbose_name='ชื่อมาตรฐาน'),
        ),
        migrations.AlterField(
            model_name='standard',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไขล่าสุด'),
        ),
    ]
