# Generated by Django 5.2.4 on 2025-09-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('std', '0002_alter_standard_options_alter_standard_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='standard',
            name='asset_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='หมายเลขทรัพย์สิน'),
        ),
        migrations.AddField(
            model_name='standard',
            name='certificate_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='หมายเลขใบรับรองมาตรฐาน'),
        ),
        migrations.AddField(
            model_name='standard',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='วันที่ครบกำหนดมาตรฐาน'),
        ),
    ]
