# Generated by Django 5.2.4 on 2025-07-12 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machine', '0001_initial'),
        ('std', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalibrationForce',
            fields=[
                ('cal_force_id', models.AutoField(primary_key=True, serialize=False)),
                ('apply_com', models.CharField(blank=True, max_length=10, null=True)),
                ('apply_ten', models.CharField(blank=True, max_length=10, null=True)),
                ('compress', models.CharField(blank=True, max_length=10, null=True)),
                ('tension', models.CharField(blank=True, max_length=10, null=True)),
                ('fullscale', models.FloatField(blank=True, null=True)),
                ('error', models.FloatField(blank=True, null=True)),
                ('uncer', models.FloatField(blank=True, null=True)),
                ('tolerance_start', models.FloatField(blank=True, null=True)),
                ('tolerance_end', models.FloatField(blank=True, null=True)),
                ('update', models.DateTimeField(blank=True, null=True)),
                ('uuc_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CalibrationPressure',
            fields=[
                ('cal_pressure_id', models.AutoField(primary_key=True, serialize=False)),
                ('set', models.CharField(blank=True, max_length=10, null=True)),
                ('m1', models.CharField(blank=True, max_length=10, null=True)),
                ('m2', models.CharField(blank=True, max_length=10, null=True)),
                ('m3', models.CharField(blank=True, max_length=10, null=True)),
                ('m4', models.CharField(blank=True, max_length=10, null=True)),
                ('avg', models.FloatField(blank=True, null=True)),
                ('error', models.FloatField(blank=True, null=True)),
                ('uncer', models.FloatField(blank=True, null=True)),
                ('tolerance_start', models.FloatField(blank=True, null=True)),
                ('tolerance_end', models.FloatField(blank=True, null=True)),
                ('update', models.DateTimeField(blank=True, null=True)),
                ('uuc_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CalibrationTorque',
            fields=[
                ('cal_torque_id', models.AutoField(primary_key=True, serialize=False)),
                ('cwset', models.FloatField(blank=True, null=True)),
                ('cw0', models.FloatField(blank=True, null=True)),
                ('cw90', models.FloatField(blank=True, null=True)),
                ('cw180', models.FloatField(blank=True, null=True)),
                ('cw270', models.FloatField(blank=True, null=True)),
                ('cw_reading', models.FloatField(blank=True, null=True)),
                ('cw_avg', models.FloatField(blank=True, null=True)),
                ('cw_error', models.FloatField(blank=True, null=True)),
                ('cw_uncen', models.FloatField(blank=True, null=True)),
                ('cw_tolerance_start', models.FloatField(blank=True, null=True)),
                ('cw_tolerance_end', models.FloatField(blank=True, null=True)),
                ('ccwset', models.FloatField(blank=True, null=True)),
                ('ccw0', models.FloatField(blank=True, null=True)),
                ('ccw90', models.FloatField(blank=True, null=True)),
                ('ccw180', models.FloatField(blank=True, null=True)),
                ('ccw270', models.FloatField(blank=True, null=True)),
                ('ccw_reading', models.FloatField(blank=True, null=True)),
                ('ccw_avg', models.FloatField(blank=True, null=True)),
                ('ccw_error', models.FloatField(blank=True, null=True)),
                ('ccw_uncen', models.FloatField(blank=True, null=True)),
                ('ccw_tolerance_start', models.FloatField(blank=True, null=True)),
                ('ccw_tolerance_end', models.FloatField(blank=True, null=True)),
                ('update', models.DateTimeField(blank=True, null=True)),
                ('uuc_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UUC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine.machine')),
                ('std', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='std.standard')),
            ],
        ),
        migrations.CreateModel(
            name='UUCStdMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='std.standard')),
                ('uuc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calibrate.uuc')),
            ],
        ),
    ]
