# Generated by Django 5.2.4 on 2025-07-12 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibrate', '0001_initial'),
        ('machine', '0002_alter_machine_options_alter_machinetype_options_and_more'),
        ('std', '0002_alter_standard_options_alter_standard_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calibrationforce',
            options={'verbose_name': 'ข้อมูลสอบเทียบแรง', 'verbose_name_plural': 'ข้อมูลสอบเทียบแรง'},
        ),
        migrations.AlterModelOptions(
            name='calibrationpressure',
            options={'verbose_name': 'ข้อมูลสอบเทียบความดัน', 'verbose_name_plural': 'ข้อมูลสอบเทียบความดัน'},
        ),
        migrations.AlterModelOptions(
            name='calibrationtorque',
            options={'verbose_name': 'ข้อมูลสอบเทียบแรงบิด', 'verbose_name_plural': 'ข้อมูลสอบเทียบแรงบิด'},
        ),
        migrations.AlterModelOptions(
            name='uuc',
            options={'verbose_name': 'เครื่องที่สอบเทียบ (UUC)', 'verbose_name_plural': 'เครื่องที่สอบเทียบ (UUC)'},
        ),
        migrations.AlterModelOptions(
            name='uucstdmap',
            options={'verbose_name': 'การเชื่อมโยง UUC กับมาตรฐาน', 'verbose_name_plural': 'การเชื่อมโยง UUC กับมาตรฐาน'},
        ),
        migrations.AlterField(
            model_name='calibrationforce',
            name='apply_com',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='แรงกด (Compression)'),
        ),
        migrations.AlterField(
            model_name='calibrationforce',
            name='apply_ten',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='แรงดึง (Tension)'),
        ),
        migrations.AlterField(
            model_name='calibrationforce',
            name='cal_force_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='รหัสการสอบเทียบแรง'),
        ),
        migrations.AlterField(
            model_name='calibrationforce',
            name='compress',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ค่ากด (Compression)'),
        ),
        migrations.AlterField(
            model_name='calibrationforce',
            name='error',
            field=models.FloatField(blank=True, null=True, verbose_name='ค่าความคลาดเคลื่อน (Error)'),
        ),
        migrations.AlterField(
            model_name='calibrationforce',
            name='fullscale',
            field=models.FloatField(blank=True, null=True, verbose_name='ค่าช่วงการวัดสูงสุด (Full Scale)'),
        ),
        migrations.AlterField(
            model_name='calibrationforce',
            name='tension',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ค่าดึง (Tension)'),
        ),
        migrations.AlterField(
            model_name='calibrationforce',
            name='tolerance_end',
            field=models.FloatField(blank=True, null=True, verbose_name='ค่าความคลาดเคลื่อนสิ้นสุด'),
        ),
        migrations.AlterField(
            model_name='calibrationforce',
            name='tolerance_start',
            field=models.FloatField(blank=True, null=True, verbose_name='ค่าความคลาดเคลื่อนเริ่มต้น'),
        ),
        migrations.AlterField(
            model_name='calibrationforce',
            name='uncer',
            field=models.FloatField(blank=True, null=True, verbose_name='ค่าความไม่แน่นอน (Uncertainty)'),
        ),
        migrations.AlterField(
            model_name='calibrationforce',
            name='update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='วันที่อัปเดต'),
        ),
        migrations.AlterField(
            model_name='calibrationforce',
            name='uuc_id',
            field=models.IntegerField(verbose_name='รหัสเครื่องที่สอบเทียบ (UUC)'),
        ),
        migrations.AlterField(
            model_name='calibrationpressure',
            name='avg',
            field=models.FloatField(blank=True, null=True, verbose_name='ค่าเฉลี่ย'),
        ),
        migrations.AlterField(
            model_name='calibrationpressure',
            name='cal_pressure_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='รหัสการสอบเทียบความดัน'),
        ),
        migrations.AlterField(
            model_name='calibrationpressure',
            name='error',
            field=models.FloatField(blank=True, null=True, verbose_name='ค่าความคลาดเคลื่อน (Error)'),
        ),
        migrations.AlterField(
            model_name='calibrationpressure',
            name='m1',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ค่าที่ 1'),
        ),
        migrations.AlterField(
            model_name='calibrationpressure',
            name='m2',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ค่าที่ 2'),
        ),
        migrations.AlterField(
            model_name='calibrationpressure',
            name='m3',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ค่าที่ 3'),
        ),
        migrations.AlterField(
            model_name='calibrationpressure',
            name='m4',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ค่าที่ 4'),
        ),
        migrations.AlterField(
            model_name='calibrationpressure',
            name='set',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ค่าตั้งต้น'),
        ),
        migrations.AlterField(
            model_name='calibrationpressure',
            name='tolerance_end',
            field=models.FloatField(blank=True, null=True, verbose_name='ค่าความคลาดเคลื่อนสิ้นสุด'),
        ),
        migrations.AlterField(
            model_name='calibrationpressure',
            name='tolerance_start',
            field=models.FloatField(blank=True, null=True, verbose_name='ค่าความคลาดเคลื่อนเริ่มต้น'),
        ),
        migrations.AlterField(
            model_name='calibrationpressure',
            name='uncer',
            field=models.FloatField(blank=True, null=True, verbose_name='ค่าความไม่แน่นอน (Uncertainty)'),
        ),
        migrations.AlterField(
            model_name='calibrationpressure',
            name='update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='วันที่อัปเดต'),
        ),
        migrations.AlterField(
            model_name='calibrationpressure',
            name='uuc_id',
            field=models.IntegerField(verbose_name='รหัสเครื่องที่สอบเทียบ (UUC)'),
        ),
        migrations.AlterField(
            model_name='calibrationtorque',
            name='cal_torque_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='รหัสการสอบเทียบแรงบิด'),
        ),
        migrations.AlterField(
            model_name='calibrationtorque',
            name='ccw0',
            field=models.FloatField(blank=True, null=True, verbose_name='CCW 0 องศา'),
        ),
        migrations.AlterField(
            model_name='calibrationtorque',
            name='ccw180',
            field=models.FloatField(blank=True, null=True, verbose_name='CCW 180 องศา'),
        ),
        migrations.AlterField(
            model_name='calibrationtorque',
            name='ccw270',
            field=models.FloatField(blank=True, null=True, verbose_name='CCW 270 องศา'),
        ),
        migrations.AlterField(
            model_name='calibrationtorque',
            name='ccw90',
            field=models.FloatField(blank=True, null=True, verbose_name='CCW 90 องศา'),
        ),
        migrations.AlterField(
            model_name='calibrationtorque',
            name='ccw_avg',
            field=models.FloatField(blank=True, null=True, verbose_name='ค่าเฉลี่ย CCW'),
        ),
        migrations.AlterField(
            model_name='calibrationtorque',
            name='ccw_error',
            field=models.FloatField(blank=True, null=True, verbose_name='ค่าความคลาดเคลื่อน CCW'),
        ),
        migrations.AlterField(
            model_name='calibrationtorque',
            name='ccw_reading',
            field=models.FloatField(blank=True, null=True, verbose_name='ค่าอ่าน CCW'),
        ),
        migrations.AlterField(
            model_name='calibrationtorque',
            name='ccw_tolerance_end',
            field=models.FloatField(blank=True, null=True, verbose_name='ค่าความคลาดเคลื่อนสิ้นสุด CCW'),
        ),
        migrations.AlterField(
            model_name='calibrationtorque',
            name='ccw_tolerance_start',
            field=models.FloatField(blank=True, null=True, verbose_name='ค่าความคลาดเคลื่อนเริ่มต้น CCW'),
        ),
        migrations.AlterField(
            model_name='calibrationtorque',
            name='ccw_uncen',
            field=models.FloatField(blank=True, null=True, verbose_name='ค่าความไม่แน่นอน CCW'),
        ),
        migrations.AlterField(
            model_name='calibrationtorque',
            name='ccwset',
            field=models.FloatField(blank=True, null=True, verbose_name='ตั้งค่า CCW'),
        ),
        migrations.AlterField(
            model_name='calibrationtorque',
            name='cw0',
            field=models.FloatField(blank=True, null=True, verbose_name='CW 0 องศา'),
        ),
        migrations.AlterField(
            model_name='calibrationtorque',
            name='cw180',
            field=models.FloatField(blank=True, null=True, verbose_name='CW 180 องศา'),
        ),
        migrations.AlterField(
            model_name='calibrationtorque',
            name='cw270',
            field=models.FloatField(blank=True, null=True, verbose_name='CW 270 องศา'),
        ),
        migrations.AlterField(
            model_name='calibrationtorque',
            name='cw90',
            field=models.FloatField(blank=True, null=True, verbose_name='CW 90 องศา'),
        ),
        migrations.AlterField(
            model_name='calibrationtorque',
            name='cw_avg',
            field=models.FloatField(blank=True, null=True, verbose_name='ค่าเฉลี่ย CW'),
        ),
        migrations.AlterField(
            model_name='calibrationtorque',
            name='cw_error',
            field=models.FloatField(blank=True, null=True, verbose_name='ค่าความคลาดเคลื่อน CW'),
        ),
        migrations.AlterField(
            model_name='calibrationtorque',
            name='cw_reading',
            field=models.FloatField(blank=True, null=True, verbose_name='ค่าอ่าน CW'),
        ),
        migrations.AlterField(
            model_name='calibrationtorque',
            name='cw_tolerance_end',
            field=models.FloatField(blank=True, null=True, verbose_name='ค่าความคลาดเคลื่อนสิ้นสุด CW'),
        ),
        migrations.AlterField(
            model_name='calibrationtorque',
            name='cw_tolerance_start',
            field=models.FloatField(blank=True, null=True, verbose_name='ค่าความคลาดเคลื่อนเริ่มต้น CW'),
        ),
        migrations.AlterField(
            model_name='calibrationtorque',
            name='cw_uncen',
            field=models.FloatField(blank=True, null=True, verbose_name='ค่าความไม่แน่นอน CW'),
        ),
        migrations.AlterField(
            model_name='calibrationtorque',
            name='cwset',
            field=models.FloatField(blank=True, null=True, verbose_name='ตั้งค่า CW'),
        ),
        migrations.AlterField(
            model_name='calibrationtorque',
            name='update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='วันที่อัปเดต'),
        ),
        migrations.AlterField(
            model_name='calibrationtorque',
            name='uuc_id',
            field=models.IntegerField(verbose_name='รหัสเครื่องที่สอบเทียบ (UUC)'),
        ),
        migrations.AlterField(
            model_name='uuc',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine.machine', verbose_name='เครื่องมือ'),
        ),
        migrations.AlterField(
            model_name='uuc',
            name='name',
            field=models.CharField(max_length=100, verbose_name='ชื่อเครื่องที่สอบเทียบ (UUC)'),
        ),
        migrations.AlterField(
            model_name='uuc',
            name='std',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='std.standard', verbose_name='มาตรฐาน'),
        ),
        migrations.AlterField(
            model_name='uucstdmap',
            name='std',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='std.standard', verbose_name='มาตรฐาน'),
        ),
        migrations.AlterField(
            model_name='uucstdmap',
            name='uuc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calibrate.uuc', verbose_name='เครื่องที่สอบเทียบ (UUC)'),
        ),
    ]
