# Generated by Django 5.2.4 on 2025-07-30 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibrate', '0002_alter_calibrationforce_options_and_more'),
        ('machine', '0003_remove_machine_organize_id_machine_organize_and_more'),
        ('std', '0002_alter_standard_options_alter_standard_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibrationforce',
            name='next_due',
            field=models.DateField(blank=True, null=True, verbose_name='วันที่ครบกำหนดสอบเทียบถัดไป'),
        ),
        migrations.AddField(
            model_name='calibrationforce',
            name='std_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='std.standard', verbose_name='มาตรฐานที่ใช้'),
        ),
        migrations.AddField(
            model_name='calibrationpressure',
            name='next_due',
            field=models.DateField(blank=True, null=True, verbose_name='วันที่ครบกำหนดสอบเทียบถัดไป'),
        ),
        migrations.AddField(
            model_name='calibrationpressure',
            name='std_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='std.standard', verbose_name='มาตรฐานที่ใช้'),
        ),
        migrations.AddField(
            model_name='calibrationtorque',
            name='next_due',
            field=models.DateField(blank=True, null=True, verbose_name='วันที่ครบกำหนดสอบเทียบถัดไป'),
        ),
        migrations.AddField(
            model_name='calibrationtorque',
            name='std_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='std.standard', verbose_name='มาตรฐานที่ใช้'),
        ),
        migrations.AlterField(
            model_name='calibrationforce',
            name='update',
            field=models.DateField(blank=True, null=True, verbose_name='วันที่ calibration'),
        ),
        migrations.AlterField(
            model_name='calibrationforce',
            name='uuc_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine.machine', verbose_name='เครื่องมือที่สอบเทียบ'),
        ),
        migrations.AlterField(
            model_name='calibrationpressure',
            name='update',
            field=models.DateField(blank=True, null=True, verbose_name='วันที่ calibration'),
        ),
        migrations.AlterField(
            model_name='calibrationpressure',
            name='uuc_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine.machine', verbose_name='เครื่องมือที่สอบเทียบ'),
        ),
        migrations.AlterField(
            model_name='calibrationtorque',
            name='update',
            field=models.DateField(blank=True, null=True, verbose_name='วันที่ calibration'),
        ),
        migrations.AlterField(
            model_name='calibrationtorque',
            name='uuc_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine.machine', verbose_name='เครื่องมือที่สอบเทียบ'),
        ),
    ]
