# Generated by Django 5.2.4 on 2025-07-30 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibrate', '0003_calibrationforce_next_due_calibrationforce_std_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibrationforce',
            name='priority',
            field=models.CharField(choices=[('normal', 'ปกติ'), ('urgent', 'ด่วน'), ('very_urgent', 'ด่วนมาก')], default='normal', max_length=20, verbose_name='ระดับความเร่งด่วน'),
        ),
        migrations.AddField(
            model_name='calibrationforce',
            name='status',
            field=models.CharField(choices=[('active', 'ปกติ'), ('expired', 'หมดอายุ'), ('expiring_soon', 'ใกล้หมดอายุ'), ('not_set', 'ไม่ระบุ')], default='not_set', max_length=20, verbose_name='สถานะ'),
        ),
        migrations.AddField(
            model_name='calibrationpressure',
            name='priority',
            field=models.CharField(choices=[('normal', 'ปกติ'), ('urgent', 'ด่วน'), ('very_urgent', 'ด่วนมาก')], default='normal', max_length=20, verbose_name='ระดับความเร่งด่วน'),
        ),
        migrations.AddField(
            model_name='calibrationpressure',
            name='status',
            field=models.CharField(choices=[('active', 'ปกติ'), ('expired', 'หมดอายุ'), ('expiring_soon', 'ใกล้หมดอายุ'), ('not_set', 'ไม่ระบุ')], default='not_set', max_length=20, verbose_name='สถานะ'),
        ),
        migrations.AddField(
            model_name='calibrationtorque',
            name='priority',
            field=models.CharField(choices=[('normal', 'ปกติ'), ('urgent', 'ด่วน'), ('very_urgent', 'ด่วนมาก')], default='normal', max_length=20, verbose_name='ระดับความเร่งด่วน'),
        ),
        migrations.AddField(
            model_name='calibrationtorque',
            name='status',
            field=models.CharField(choices=[('active', 'ปกติ'), ('expired', 'หมดอายุ'), ('expiring_soon', 'ใกล้หมดอายุ'), ('not_set', 'ไม่ระบุ')], default='not_set', max_length=20, verbose_name='สถานะ'),
        ),
    ]
