# Generated by Django 5.2.4 on 2025-08-03 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibrate', '0005_alter_calibrationforce_status_and_more'),
        ('std', '0002_alter_standard_options_alter_standard_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibrationforce',
            name='std_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='std.standard', verbose_name='เครื่องมือที่ใช้สอบเทียบ'),
        ),
        migrations.AlterField(
            model_name='calibrationpressure',
            name='std_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='std.standard', verbose_name='เครื่องมือที่ใช้สอบเทียบ'),
        ),
        migrations.AlterField(
            model_name='calibrationtorque',
            name='std_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='std.standard', verbose_name='เครื่องมือที่ใช้สอบเทียบ'),
        ),
    ]
