# Generated by Django 5.2.4 on 2025-08-15 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibrate', '0006_alter_calibrationforce_std_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='calibrationforce',
            name='calibrator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='force_calibrations', to=settings.AUTH_USER_MODEL, verbose_name='ผู้สอบเทียบ'),
        ),
        migrations.AddField(
            model_name='calibrationforce',
            name='certificate_issuer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='force_certificates', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ออกใบรับรอง'),
        ),
        migrations.AddField(
            model_name='calibrationpressure',
            name='calibrator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pressure_calibrations', to=settings.AUTH_USER_MODEL, verbose_name='ผู้สอบเทียบ'),
        ),
        migrations.AddField(
            model_name='calibrationpressure',
            name='certificate_issuer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pressure_certificates', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ออกใบรับรอง'),
        ),
        migrations.AddField(
            model_name='calibrationtorque',
            name='calibrator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='torque_calibrations', to=settings.AUTH_USER_MODEL, verbose_name='ผู้สอบเทียบ'),
        ),
        migrations.AddField(
            model_name='calibrationtorque',
            name='certificate_issuer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='torque_certificates', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ออกใบรับรอง'),
        ),
    ]
