# Generated by Django 5.2.4 on 2025-08-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibrate', '0007_calibrationforce_calibrator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibrationforce',
            name='update',
            field=models.DateField(blank=True, null=True, verbose_name='วันที่สอบเทียบ'),
        ),
        migrations.AlterField(
            model_name='calibrationpressure',
            name='update',
            field=models.DateField(blank=True, null=True, verbose_name='วันที่สอบเทียบ'),
        ),
        migrations.AlterField(
            model_name='calibrationtorque',
            name='update',
            field=models.DateField(blank=True, null=True, verbose_name='วันที่สอบเทียบ'),
        ),
    ]
