# Generated by Django 5.2.4 on 2025-09-11 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibrate', '0008_alter_calibrationforce_update_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibrationforce',
            name='status',
            field=models.CharField(choices=[('pending', 'รอสอบเทียบ'), ('in_progress', 'กำลังสอบเทียบ'), ('passed', 'ผ่านการสอบเทียบ'), ('cert_issued', 'ออกใบรับรอง'), ('failed', 'ไม่ผ่านการสอบเทียบ'), ('closed', 'ปิดงาน')], default='pending', max_length=20, verbose_name='สถานะสอบเทียบ'),
        ),
        migrations.AlterField(
            model_name='calibrationpressure',
            name='status',
            field=models.CharField(choices=[('pending', 'รอสอบเทียบ'), ('in_progress', 'กำลังสอบเทียบ'), ('passed', 'ผ่านการสอบเทียบ'), ('cert_issued', 'ออกใบรับรอง'), ('failed', 'ไม่ผ่านการสอบเทียบ'), ('closed', 'ปิดงาน')], default='pending', max_length=20, verbose_name='สถานะสอบเทียบ'),
        ),
        migrations.AlterField(
            model_name='calibrationtorque',
            name='status',
            field=models.CharField(choices=[('pending', 'รอสอบเทียบ'), ('in_progress', 'กำลังสอบเทียบ'), ('passed', 'ผ่านการสอบเทียบ'), ('cert_issued', 'ออกใบรับรอง'), ('failed', 'ไม่ผ่านการสอบเทียบ'), ('closed', 'ปิดงาน')], default='not_set', max_length=20, verbose_name='สถานะปรับเเทียบ'),
        ),
    ]
