# Generated by Django 5.2.4 on 2025-09-11 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibrate', '0009_alter_calibrationforce_status_and_more'),
        ('machine', '0006_alter_calibrationequipment_certificate'),
        ('std', '0002_alter_standard_options_alter_standard_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DialGaugeCalibration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_calibration', models.DateField(verbose_name='วันที่สอบเทียบ')),
                ('update', models.DateField(blank=True, null=True, verbose_name='วันที่อัปเดต')),
                ('next_due', models.DateField(blank=True, null=True, verbose_name='วันที่ครบกำหนดสอบเทียบถัดไป')),
                ('res_uuc', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='ความละเอียด UUC (inch)')),
                ('acc_std', models.DecimalField(decimal_places=8, max_digits=10, verbose_name='ความแม่นยำมาตรฐาน (inch)')),
                ('status', models.CharField(choices=[('pending', 'รอสอบเทียบ'), ('in_progress', 'กำลังสอบเทียบ'), ('passed', 'ผ่านการสอบเทียบ'), ('cert_issued', 'ออกใบรับรอง'), ('failed', 'ไม่ผ่านการสอบเทียบ'), ('closed', 'ปิดงาน')], default='pending', max_length=20, verbose_name='สถานะสอบเทียบ')),
                ('priority', models.CharField(choices=[('normal', 'ปกติ'), ('urgent', 'ด่วน'), ('very_urgent', 'ด่วนมาก')], default='normal', max_length=20, verbose_name='ระดับความเร่งด่วน')),
                ('type_a_sd', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Type A (SD)')),
                ('type_b_res_uuc', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Type B Res.UUC')),
                ('type_b_acc_std', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Type B Acc.STD')),
                ('type_b_hysteresis', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Type B Hysteresis')),
                ('uc_68', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Uc 68%')),
                ('k_factor', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='K')),
                ('expanded_uncertainty_95', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='95%')),
                ('calibrator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dial_gauge_calibrations', to=settings.AUTH_USER_MODEL, verbose_name='ผู้สอบเทียบ')),
                ('certificate_issuer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dial_gauge_certificates', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ออกใบรับรอง')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine.machine', verbose_name='เครื่องมือ Dial Gauge')),
                ('std_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='std.standard', verbose_name='เครื่องมือที่ใช้สอบเทียบ')),
            ],
            options={
                'verbose_name': 'ข้อมูลสอบเทียบ Dial Gauge',
                'verbose_name_plural': 'ข้อมูลสอบเทียบ Dial Gauge',
            },
        ),
        migrations.CreateModel(
            name='DialGaugeReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuc_set', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='UUC.Set (Inch)')),
                ('std_read_up1', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='STD.Read Up1 (Inch)')),
                ('std_read_down1', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='STD.Read Down1 (Inch)')),
                ('std_read_up2', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='STD.Read Up2 (Inch)')),
                ('std_read_down2', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='STD.Read Down2 (Inch)')),
                ('average_up', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Average Up')),
                ('average_down', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Average Down')),
                ('error', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Error')),
                ('uncertainty', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Uncer. ± (inch)')),
                ('hysteresis', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Hysteresis')),
                ('value_root2', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='ค่ารูท2')),
                ('value_root3', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='ค่ารูท3')),
                ('value_2root3', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='ค่า2รูท3')),
                ('calibration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='calibrate.dialgaugecalibration', verbose_name='การสอบเทียบ')),
            ],
            options={
                'verbose_name': 'ข้อมูลการอ่านค่า Dial Gauge',
                'verbose_name_plural': 'ข้อมูลการอ่านค่า Dial Gauge',
            },
        ),
    ]
