# Generated by Django 5.2.4 on 2025-09-11 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibrate', '0010_dialgaugecalibration_dialgaugereading'),
        ('machine', '0006_alter_calibrationequipment_certificate'),
        ('std', '0002_alter_standard_options_alter_standard_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceCalibration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_calibration', models.DateField(verbose_name='วันที่สอบเทียบ')),
                ('update', models.DateField(blank=True, null=True, verbose_name='วันที่อัปเดต')),
                ('next_due', models.DateField(blank=True, null=True, verbose_name='วันที่ครบกำหนดสอบเทียบถัดไป')),
                ('unit', models.CharField(default='mg', max_length=20, verbose_name='หน่วย')),
                ('status', models.CharField(choices=[('pending', 'รอสอบเทียบ'), ('in_progress', 'กำลังสอบเทียบ'), ('passed', 'ผ่านการสอบเทียบ'), ('cert_issued', 'ออกใบรับรอง'), ('failed', 'ไม่ผ่านการสอบเทียบ'), ('closed', 'ปิดงาน')], default='pending', max_length=20, verbose_name='สถานะสอบเทียบ')),
                ('priority', models.CharField(choices=[('normal', 'ปกติ'), ('urgent', 'ด่วน'), ('very_urgent', 'ด่วนมาก')], default='normal', max_length=20, verbose_name='ระดับความเร่งด่วน')),
                ('drift', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Drift')),
                ('res_push', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='RES.ดัน')),
                ('res_tip', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='RES.ปลาย')),
                ('air_buoyancy', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Air Biyou')),
                ('uncertainty_68', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Uncer 68%')),
                ('uncertainty_95_k', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='95%*K')),
                ('final_uncertainty', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Final Uncer')),
                ('calibrator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balance_calibrations', to=settings.AUTH_USER_MODEL, verbose_name='ผู้สอบเทียบ')),
                ('certificate_issuer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balance_certificates', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ออกใบรับรอง')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine.machine', verbose_name='เครื่องมือ Balance')),
                ('std_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='std.standard', verbose_name='เครื่องมือที่ใช้สอบเทียบ')),
            ],
            options={
                'verbose_name': 'ข้อมูลสอบเทียบ Balance',
                'verbose_name_plural': 'ข้อมูลสอบเทียบ Balance',
            },
        ),
        migrations.CreateModel(
            name='BalanceReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuc_set', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='UUC.set')),
                ('std_read_1', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='STD.Read 1')),
                ('std_read_2', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='STD.Read 2')),
                ('std_read_3', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='STD.Read 3')),
                ('std_read_4', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='STD.Read 4')),
                ('std_read_5', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='STD.Read 5')),
                ('std_read_6', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='STD.Read 6')),
                ('std_read_7', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='STD.Read 7')),
                ('std_read_8', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='STD.Read 8')),
                ('std_read_9', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='STD.Read 9')),
                ('std_read_10', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='STD.Read 10')),
                ('average', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='Avg')),
                ('standard_deviation', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='SD')),
                ('uncertainty', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Uncer')),
                ('calibration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='calibrate.balancecalibration', verbose_name='การสอบเทียบ')),
            ],
            options={
                'verbose_name': 'ข้อมูลการอ่านค่า Balance',
                'verbose_name_plural': 'ข้อมูลการอ่านค่า Balance',
            },
        ),
    ]
