# Generated by Django 5.2.4 on 2025-09-11 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibrate', '0011_balancecalibration_balancereading'),
        ('machine', '0006_alter_calibrationequipment_certificate'),
        ('std', '0002_alter_standard_options_alter_standard_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MicrowaveCalibration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_calibration', models.DateField(verbose_name='วันที่สอบเทียบ')),
                ('update', models.DateField(blank=True, null=True, verbose_name='วันที่อัปเดต')),
                ('next_due', models.DateField(blank=True, null=True, verbose_name='วันที่ครบกำหนดสอบเทียบถัดไป')),
                ('certificate_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='หมายเลขใบรับรอง')),
                ('status', models.CharField(choices=[('pending', 'รอปรับเทียบ'), ('in_progress', 'กำลังปรับเทียบ'), ('passed', 'ผ่านการปรับเทียบ'), ('cert_issued', 'ออกใบรับรอง'), ('failed', 'ไม่ผ่านการสอบเทียบ'), ('closed', 'ปิดงาน')], default='pending', max_length=20, verbose_name='สถานะปรับเทียบ')),
                ('priority', models.CharField(choices=[('normal', 'ปกติ'), ('urgent', 'ด่วน'), ('very_urgent', 'ด่วนมาก')], default='normal', max_length=20, verbose_name='ระดับความเร่งด่วน')),
                ('calibrator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='microwave_calibrations', to=settings.AUTH_USER_MODEL, verbose_name='ผู้สอบเทียบ')),
                ('certificate_issuer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='microwave_certificates', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ออกใบรับรอง')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine.machine', verbose_name='เครื่องมือ Microwave')),
                ('std_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='std.standard', verbose_name='เครื่องมือที่ใช้สอบเทียบ')),
            ],
            options={
                'verbose_name': 'ข้อมูลสอบเทียบ Microwave',
                'verbose_name_plural': 'ข้อมูลสอบเทียบ Microwave',
            },
        ),
        migrations.CreateModel(
            name='MicrowaveReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('output_level_ant', 'OUTPUT LEVEL @ ANT PORT CALIBRATION'), ('output_level_rf', 'OUTPUT LEVEL @ RF I/O PORT CALIBRATION'), ('dme_reply_pulse', 'DME REPLY PULSE CHARACTERISTICS CALIBRATION'), ('dme_reply_delay', 'DME REPLY DELAY RANGE CALIBRATION'), ('dme_reply_position', 'DME REPLY POSITION AND AMPLITUDE CALIBRATION'), ('dme_reply_efficiency', 'DME REPLY REPLY EFFICIENCY CALIBRATION'), ('dme_squitter', 'DME SQUITTER CALIBRATION'), ('dme_interrogation_timing', 'DME MEASUREMENT - INTERROGATION PULSE TIMING CALIBRATION'), ('dme_interrogation_prf', 'DME MEASUREMENT-INTERROGATION PRF CALIBRATION'), ('dme_interrogation_freq', 'DME MEASUREMENT-INTERROGATION FREQUENCY CALIBRATION'), ('xpdr_pulse_atcrbs', 'XPDR PULSE CHARACTERISTICS-ATCRBS CALIBRATION'), ('xpdr_pulse_mode_s', 'XPDR PULSE CHARACTERISTICS-MODE S CALIBRATION'), ('xpdr_interrogation_prf', 'XPDR INTERROGATION PRF CALIBRATION'), ('xpdr_sls_level', 'XPDR SLS LEVEL CALIBRATION')], max_length=50, verbose_name='ประเภทการทดสอบ')),
                ('function_test', models.CharField(blank=True, max_length=200, null=True, verbose_name='Function Test')),
                ('nominal_value', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nominal Value')),
                ('rf_level', models.CharField(blank=True, max_length=100, null=True, verbose_name='RF Level')),
                ('frequency', models.CharField(blank=True, max_length=100, null=True, verbose_name='Frequency')),
                ('measured_value', models.CharField(blank=True, max_length=100, null=True, verbose_name='Measured Value')),
                ('measured_value_numeric', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True, verbose_name='Measured Value (Numeric)')),
                ('unit', models.CharField(blank=True, max_length=20, null=True, verbose_name='Unit')),
                ('uncertainty', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Uncertainty (±)')),
                ('tolerance_limit_min', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True, verbose_name='Tolerance Limit Min')),
                ('tolerance_limit_max', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True, verbose_name='Tolerance Limit Max')),
                ('test_result', models.CharField(blank=True, choices=[('pass', 'ผ่าน'), ('fail', 'ไม่ผ่าน')], max_length=20, null=True, verbose_name='ผลการทดสอบ')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='หมายเหตุ')),
                ('calibration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='calibrate.microwavecalibration', verbose_name='การสอบเทียบ')),
            ],
            options={
                'verbose_name': 'ข้อมูลการอ่านค่า Microwave',
                'verbose_name_plural': 'ข้อมูลการอ่านค่า Microwave',
            },
        ),
    ]
