# Generated by Django 5.2.4 on 2025-09-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibrate', '0012_microwavecalibration_microwavereading'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancecalibration',
            name='certificate_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='หมายเลขใบรับรอง'),
        ),
        migrations.AddField(
            model_name='balancecalibration',
            name='issue_date',
            field=models.DateField(blank=True, null=True, verbose_name='วันที่ออกใบรับรอง'),
        ),
        migrations.AddField(
            model_name='balancecalibration',
            name='procedure_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='หมายเลขขั้นตอนการสอบเทียบ'),
        ),
        migrations.AddField(
            model_name='balancecalibration',
            name='received_date',
            field=models.DateField(blank=True, null=True, verbose_name='วันที่รับเครื่องมือ'),
        ),
        migrations.AddField(
            model_name='balancereading',
            name='conventional_mass',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='Conventional Mass'),
        ),
        migrations.AddField(
            model_name='balancereading',
            name='displayed_value',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='Displayed Value'),
        ),
    ]
