# Generated by Django 5.2.4 on 2025-09-24 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibrate', '0013_balancecalibration_certificate_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibrationforce',
            name='certificate_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='หมายเลขใบรับรอง'),
        ),
        migrations.AddField(
            model_name='calibrationpressure',
            name='certificate_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='หมายเลขใบรับรอง'),
        ),
        migrations.AddField(
            model_name='calibrationtorque',
            name='certificate_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='หมายเลขใบรับรอง'),
        ),
    ]
