# Generated by Django 5.2.4 on 2025-09-24 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibrate', '0014_calibrationforce_certificate_number_and_more'),
        ('machine', '0007_machine_customer_asset_id_machine_option'),
        ('std', '0003_standard_asset_number_standard_certificate_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HighFrequencyCalibration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_calibration', models.DateField(verbose_name='วันที่สอบเทียบ')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='วันที่อัปเดต')),
                ('next_due', models.DateField(verbose_name='วันที่ครบกำหนดสอบเทียบถัดไป')),
                ('certificate_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='หมายเลขใบรับรอง')),
                ('status', models.CharField(choices=[('pending', 'รอสอบเทียบ'), ('in_progress', 'กำลังสอบเทียบ'), ('passed', 'ผ่านการสอบเทียบ'), ('cert_issued', 'ออกใบรับรอง'), ('failed', 'ไม่ผ่านการสอบเทียบ'), ('closed', 'ปิดงาน')], default='pending', max_length=20, verbose_name='สถานะการสอบเทียบ')),
                ('priority', models.CharField(choices=[('normal', 'ปกติ'), ('urgent', 'ด่วน'), ('very_urgent', 'ด่วนมาก')], default='normal', max_length=20, verbose_name='ระดับความเร่งด่วน')),
                ('freq_uuc_range', models.CharField(blank=True, max_length=50, null=True, verbose_name='UUC Range (Time Base)')),
                ('freq_uuc_setting', models.CharField(blank=True, max_length=50, null=True, verbose_name='UUC Setting')),
                ('freq_measured_value', models.CharField(blank=True, max_length=50, null=True, verbose_name='Measured Value')),
                ('freq_uncertainty', models.CharField(blank=True, max_length=50, null=True, verbose_name='Uncertainty (±)')),
                ('freq_tolerance_limit', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tolerance Limit')),
                ('volt_uuc_range', models.CharField(blank=True, max_length=50, null=True, verbose_name='UUC Range (Voltage)')),
                ('volt_uuc_setting', models.CharField(blank=True, max_length=50, null=True, verbose_name='UUC Setting')),
                ('volt_measured_value', models.CharField(blank=True, max_length=50, null=True, verbose_name='Measured Value')),
                ('volt_uncertainty', models.CharField(blank=True, max_length=50, null=True, verbose_name='Uncertainty (±)')),
                ('volt_tolerance_limit', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tolerance Limit')),
                ('calibrator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='high_frequency_calibrations', to=settings.AUTH_USER_MODEL, verbose_name='ผู้สอบเทียบ')),
                ('certificate_issuer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='high_frequency_certificates', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ออกใบรับรอง')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine.machine', verbose_name='เครื่องมือ High Frequency')),
                ('std_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='std.standard', verbose_name='เครื่องมือที่ใช้สอบเทียบ')),
            ],
            options={
                'verbose_name': 'การสอบเทียบ High Frequency',
                'verbose_name_plural': 'การสอบเทียบ High Frequency',
            },
        ),
    ]
