# Generated by Django 5.2.4 on 2025-09-24 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibrate', '0016_lowfrequencycalibration'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancecalibration',
            name='linear_conventional_mass',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Conventional Mass (g)'),
        ),
        migrations.AddField(
            model_name='balancecalibration',
            name='linear_displayed_value',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Displayed Value (g)'),
        ),
        migrations.AddField(
            model_name='balancecalibration',
            name='linear_error',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Error (g)'),
        ),
        migrations.AddField(
            model_name='balancecalibration',
            name='linear_nominal_value',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nominal Value (g)'),
        ),
        migrations.AddField(
            model_name='balancecalibration',
            name='linear_tolerance_limit',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tolerance Limit'),
        ),
        migrations.AddField(
            model_name='balancecalibration',
            name='linear_uncertainty',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Uncertainty (g)'),
        ),
    ]
