# Generated by Django 5.2.4 on 2025-09-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibrate', '0017_balancecalibration_linear_conventional_mass_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialgaugecalibration',
            name='actual',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Actual( inch )'),
        ),
        migrations.AddField(
            model_name='dialgaugecalibration',
            name='error',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Error( inch )'),
        ),
        migrations.AddField(
            model_name='dialgaugecalibration',
            name='tolerance_limit',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tolerance Limit'),
        ),
        migrations.AddField(
            model_name='dialgaugecalibration',
            name='uncertainty',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Uncertainty (g)'),
        ),
        migrations.AddField(
            model_name='dialgaugecalibration',
            name='uuc_set',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='UUC.Set( inch )'),
        ),
    ]
