# Generated by Django 5.2.4 on 2025-09-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibrate', '0018_dialgaugecalibration_actual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='microwavecalibration',
            name='dc_measured_value',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Measured Value (DC)'),
        ),
        migrations.AddField(
            model_name='microwavecalibration',
            name='dc_tolerance_limit',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tolerance Limit (DC)'),
        ),
        migrations.AddField(
            model_name='microwavecalibration',
            name='dc_uncertainty',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Uncertainty (±) (DC)'),
        ),
        migrations.AddField(
            model_name='microwavecalibration',
            name='dc_uuc_range',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='UUC Range (DC)'),
        ),
        migrations.AddField(
            model_name='microwavecalibration',
            name='dc_uuc_setting',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='UUC Setting (DC)'),
        ),
    ]
