# Generated by Django 5.2.4 on 2025-09-24 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibrate', '0019_microwavecalibration_dc_measured_value_and_more'),
        ('machine', '0007_machine_customer_asset_id_machine_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancecalibration',
            name='uuc_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='balance_uuc_calibrations', to='machine.machine', verbose_name='เครื่องมือที่สอบเทียบ'),
        ),
    ]
