# Generated by Django 5.2.4 on 2025-09-24 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibrate', '0020_balancecalibration_uuc_id'),
        ('machine', '0007_machine_customer_asset_id_machine_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancecalibration',
            name='std_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machine.calibrationequipment', verbose_name='เครื่องมือที่ใช้สอบเทียบ'),
        ),
        migrations.AlterField(
            model_name='calibrationforce',
            name='std_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machine.calibrationequipment', verbose_name='เครื่องมือที่ใช้สอบเทียบ'),
        ),
        migrations.AlterField(
            model_name='calibrationpressure',
            name='std_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machine.calibrationequipment', verbose_name='เครื่องมือที่ใช้สอบเทียบ'),
        ),
        migrations.AlterField(
            model_name='calibrationtorque',
            name='std_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machine.calibrationequipment', verbose_name='เครื่องมือที่ใช้สอบเทียบ'),
        ),
        migrations.AlterField(
            model_name='dialgaugecalibration',
            name='std_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machine.calibrationequipment', verbose_name='เครื่องมือที่ใช้สอบเทียบ'),
        ),
        migrations.AlterField(
            model_name='highfrequencycalibration',
            name='std_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machine.calibrationequipment', verbose_name='เครื่องมือที่ใช้สอบเทียบ'),
        ),
        migrations.AlterField(
            model_name='lowfrequencycalibration',
            name='std_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machine.calibrationequipment', verbose_name='เครื่องมือที่ใช้สอบเทียบ'),
        ),
        migrations.AlterField(
            model_name='microwavecalibration',
            name='std_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machine.calibrationequipment', verbose_name='เครื่องมือที่ใช้สอบเทียบ'),
        ),
    ]
