# Generated by Django 5.2.4 on 2025-09-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibrate', '0021_alter_balancecalibration_std_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibrationforce',
            name='std_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.CASCADE, to='machine.calibrationequipment', verbose_name='เครื่องมือที่ใช้สอบเทียบ'),
        ),
        migrations.AlterField(
            model_name='calibrationpressure',
            name='std_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.CASCADE, to='machine.calibrationequipment', verbose_name='เครื่องมือที่ใช้สอบเทียบ'),
        ),
        migrations.AlterField(
            model_name='calibrationtorque',
            name='std_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.CASCADE, to='machine.calibrationequipment', verbose_name='เครื่องมือที่ใช้สอบเทียบ'),
        ),
    ]
