# Generated by Django 5.2.4 on 2025-09-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibrate', '0022_auto_20250924_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibrationpressure',
            name='avg_2',
            field=models.FloatField(blank=True, null=True, verbose_name='ค่าเฉลี่ย (แถว 2)'),
        ),
        migrations.AddField(
            model_name='calibrationpressure',
            name='avg_3',
            field=models.FloatField(blank=True, null=True, verbose_name='ค่าเฉลี่ย (แถว 3)'),
        ),
        migrations.AddField(
            model_name='calibrationpressure',
            name='avg_4',
            field=models.FloatField(blank=True, null=True, verbose_name='ค่าเฉลี่ย (แถว 4)'),
        ),
        migrations.AddField(
            model_name='calibrationpressure',
            name='avg_5',
            field=models.FloatField(blank=True, null=True, verbose_name='ค่าเฉลี่ย (แถว 5)'),
        ),
        migrations.AddField(
            model_name='calibrationpressure',
            name='avg_6',
            field=models.FloatField(blank=True, null=True, verbose_name='ค่าเฉลี่ย (แถว 6)'),
        ),
        migrations.AddField(
            model_name='calibrationpressure',
            name='error_2',
            field=models.FloatField(blank=True, null=True, verbose_name='ค่าความคลาดเคลื่อน (แถว 2)'),
        ),
        migrations.AddField(
            model_name='calibrationpressure',
            name='error_3',
            field=models.FloatField(blank=True, null=True, verbose_name='ค่าความคลาดเคลื่อน (แถว 3)'),
        ),
        migrations.AddField(
            model_name='calibrationpressure',
            name='error_4',
            field=models.FloatField(blank=True, null=True, verbose_name='ค่าความคลาดเคลื่อน (แถว 4)'),
        ),
        migrations.AddField(
            model_name='calibrationpressure',
            name='error_5',
            field=models.FloatField(blank=True, null=True, verbose_name='ค่าความคลาดเคลื่อน (แถว 5)'),
        ),
        migrations.AddField(
            model_name='calibrationpressure',
            name='error_6',
            field=models.FloatField(blank=True, null=True, verbose_name='ค่าความคลาดเคลื่อน (แถว 6)'),
        ),
        migrations.AddField(
            model_name='calibrationpressure',
            name='m1_2',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ค่าที่ 1 (แถว 2)'),
        ),
        migrations.AddField(
            model_name='calibrationpressure',
            name='m1_3',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ค่าที่ 1 (แถว 3)'),
        ),
        migrations.AddField(
            model_name='calibrationpressure',
            name='m1_4',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ค่าที่ 1 (แถว 4)'),
        ),
        migrations.AddField(
            model_name='calibrationpressure',
            name='m1_5',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ค่าที่ 1 (แถว 5)'),
        ),
        migrations.AddField(
            model_name='calibrationpressure',
            name='m1_6',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ค่าที่ 1 (แถว 6)'),
        ),
        migrations.AddField(
            model_name='calibrationpressure',
            name='m2_2',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ค่าที่ 2 (แถว 2)'),
        ),
        migrations.AddField(
            model_name='calibrationpressure',
            name='m2_3',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ค่าที่ 2 (แถว 3)'),
        ),
        migrations.AddField(
            model_name='calibrationpressure',
            name='m2_4',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ค่าที่ 2 (แถว 4)'),
        ),
        migrations.AddField(
            model_name='calibrationpressure',
            name='m2_5',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ค่าที่ 2 (แถว 5)'),
        ),
        migrations.AddField(
            model_name='calibrationpressure',
            name='m2_6',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ค่าที่ 2 (แถว 6)'),
        ),
        migrations.AddField(
            model_name='calibrationpressure',
            name='m3_2',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ค่าที่ 3 (แถว 2)'),
        ),
        migrations.AddField(
            model_name='calibrationpressure',
            name='m3_3',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ค่าที่ 3 (แถว 3)'),
        ),
        migrations.AddField(
            model_name='calibrationpressure',
            name='m3_4',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ค่าที่ 3 (แถว 4)'),
        ),
        migrations.AddField(
            model_name='calibrationpressure',
            name='m3_5',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ค่าที่ 3 (แถว 5)'),
        ),
        migrations.AddField(
            model_name='calibrationpressure',
            name='m3_6',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ค่าที่ 3 (แถว 6)'),
        ),
        migrations.AddField(
            model_name='calibrationpressure',
            name='m4_2',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ค่าที่ 4 (แถว 2)'),
        ),
        migrations.AddField(
            model_name='calibrationpressure',
            name='m4_3',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ค่าที่ 4 (แถว 3)'),
        ),
        migrations.AddField(
            model_name='calibrationpressure',
            name='m4_4',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ค่าที่ 4 (แถว 4)'),
        ),
        migrations.AddField(
            model_name='calibrationpressure',
            name='m4_5',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ค่าที่ 4 (แถว 5)'),
        ),
        migrations.AddField(
            model_name='calibrationpressure',
            name='m4_6',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ค่าที่ 4 (แถว 6)'),
        ),
    ]
