# Generated by Django 5.2.4 on 2025-09-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibrate', '0023_calibrationpressure_avg_2_calibrationpressure_avg_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibrationpressure',
            name='set_2',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ค่าตั้งต้น (แถว 2)'),
        ),
        migrations.AddField(
            model_name='calibrationpressure',
            name='set_3',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ค่าตั้งต้น (แถว 3)'),
        ),
        migrations.AddField(
            model_name='calibrationpressure',
            name='set_4',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ค่าตั้งต้น (แถว 4)'),
        ),
        migrations.AddField(
            model_name='calibrationpressure',
            name='set_5',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ค่าตั้งต้น (แถว 5)'),
        ),
        migrations.AddField(
            model_name='calibrationpressure',
            name='set_6',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ค่าตั้งต้น (แถว 6)'),
        ),
    ]
