# Generated by Django 5.2.4 on 2025-09-24 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibrate', '0024_calibrationpressure_set_2_calibrationpressure_set_3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highfrequencycalibration',
            name='next_due',
            field=models.DateField(blank=True, null=True, verbose_name='วันที่ครบกำหนดสอบเทียบถัดไป'),
        ),
        migrations.AlterField(
            model_name='lowfrequencycalibration',
            name='next_due',
            field=models.DateField(blank=True, null=True, verbose_name='วันที่ครบกำหนดสอบเทียบถัดไป'),
        ),
    ]
