# Generated by Django 5.2.4 on 2025-09-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibrate', '0025_alter_highfrequencycalibration_next_due_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialgaugecalibration',
            name='acc_std',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='ความแม่นยำมาตรฐาน (inch)'),
        ),
        migrations.AlterField(
            model_name='dialgaugecalibration',
            name='res_uuc',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='ความละเอียด UUC (inch)'),
        ),
    ]
