# Generated by Django 5.2.4 on 2025-09-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibrate', '0026_alter_dialgaugecalibration_acc_std_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='highfrequencycalibration',
            name='freq_measured_value_2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Measured Value 2'),
        ),
        migrations.AddField(
            model_name='highfrequencycalibration',
            name='freq_measured_value_3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Measured Value 3'),
        ),
        migrations.AddField(
            model_name='highfrequencycalibration',
            name='freq_measured_value_4',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Measured Value 4'),
        ),
        migrations.AddField(
            model_name='highfrequencycalibration',
            name='freq_measured_value_5',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Measured Value 5'),
        ),
        migrations.AddField(
            model_name='highfrequencycalibration',
            name='freq_tolerance_limit_2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tolerance Limit 2'),
        ),
        migrations.AddField(
            model_name='highfrequencycalibration',
            name='freq_tolerance_limit_3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tolerance Limit 3'),
        ),
        migrations.AddField(
            model_name='highfrequencycalibration',
            name='freq_tolerance_limit_4',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tolerance Limit 4'),
        ),
        migrations.AddField(
            model_name='highfrequencycalibration',
            name='freq_tolerance_limit_5',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tolerance Limit 5'),
        ),
        migrations.AddField(
            model_name='highfrequencycalibration',
            name='freq_uncertainty_2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Uncertainty (±) 2'),
        ),
        migrations.AddField(
            model_name='highfrequencycalibration',
            name='freq_uncertainty_3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Uncertainty (±) 3'),
        ),
        migrations.AddField(
            model_name='highfrequencycalibration',
            name='freq_uncertainty_4',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Uncertainty (±) 4'),
        ),
        migrations.AddField(
            model_name='highfrequencycalibration',
            name='freq_uncertainty_5',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Uncertainty (±) 5'),
        ),
        migrations.AddField(
            model_name='highfrequencycalibration',
            name='freq_uuc_range_2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='UUC Range (Time Base) 2'),
        ),
        migrations.AddField(
            model_name='highfrequencycalibration',
            name='freq_uuc_range_3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='UUC Range (Time Base) 3'),
        ),
        migrations.AddField(
            model_name='highfrequencycalibration',
            name='freq_uuc_range_4',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='UUC Range (Time Base) 4'),
        ),
        migrations.AddField(
            model_name='highfrequencycalibration',
            name='freq_uuc_range_5',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='UUC Range (Time Base) 5'),
        ),
        migrations.AddField(
            model_name='highfrequencycalibration',
            name='freq_uuc_setting_2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='UUC Setting 2'),
        ),
        migrations.AddField(
            model_name='highfrequencycalibration',
            name='freq_uuc_setting_3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='UUC Setting 3'),
        ),
        migrations.AddField(
            model_name='highfrequencycalibration',
            name='freq_uuc_setting_4',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='UUC Setting 4'),
        ),
        migrations.AddField(
            model_name='highfrequencycalibration',
            name='freq_uuc_setting_5',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='UUC Setting 5'),
        ),
        migrations.AddField(
            model_name='highfrequencycalibration',
            name='volt_measured_value_2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Measured Value 2'),
        ),
        migrations.AddField(
            model_name='highfrequencycalibration',
            name='volt_measured_value_3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Measured Value 3'),
        ),
        migrations.AddField(
            model_name='highfrequencycalibration',
            name='volt_measured_value_4',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Measured Value 4'),
        ),
        migrations.AddField(
            model_name='highfrequencycalibration',
            name='volt_measured_value_5',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Measured Value 5'),
        ),
        migrations.AddField(
            model_name='highfrequencycalibration',
            name='volt_tolerance_limit_2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tolerance Limit 2'),
        ),
        migrations.AddField(
            model_name='highfrequencycalibration',
            name='volt_tolerance_limit_3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tolerance Limit 3'),
        ),
        migrations.AddField(
            model_name='highfrequencycalibration',
            name='volt_tolerance_limit_4',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tolerance Limit 4'),
        ),
        migrations.AddField(
            model_name='highfrequencycalibration',
            name='volt_tolerance_limit_5',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tolerance Limit 5'),
        ),
        migrations.AddField(
            model_name='highfrequencycalibration',
            name='volt_uncertainty_2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Uncertainty (±) 2'),
        ),
        migrations.AddField(
            model_name='highfrequencycalibration',
            name='volt_uncertainty_3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Uncertainty (±) 3'),
        ),
        migrations.AddField(
            model_name='highfrequencycalibration',
            name='volt_uncertainty_4',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Uncertainty (±) 4'),
        ),
        migrations.AddField(
            model_name='highfrequencycalibration',
            name='volt_uncertainty_5',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Uncertainty (±) 5'),
        ),
        migrations.AddField(
            model_name='highfrequencycalibration',
            name='volt_uuc_range_2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='UUC Range (Voltage) 2'),
        ),
        migrations.AddField(
            model_name='highfrequencycalibration',
            name='volt_uuc_range_3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='UUC Range (Voltage) 3'),
        ),
        migrations.AddField(
            model_name='highfrequencycalibration',
            name='volt_uuc_range_4',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='UUC Range (Voltage) 4'),
        ),
        migrations.AddField(
            model_name='highfrequencycalibration',
            name='volt_uuc_range_5',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='UUC Range (Voltage) 5'),
        ),
        migrations.AddField(
            model_name='highfrequencycalibration',
            name='volt_uuc_setting_2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='UUC Setting 2'),
        ),
        migrations.AddField(
            model_name='highfrequencycalibration',
            name='volt_uuc_setting_3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='UUC Setting 3'),
        ),
        migrations.AddField(
            model_name='highfrequencycalibration',
            name='volt_uuc_setting_4',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='UUC Setting 4'),
        ),
        migrations.AddField(
            model_name='highfrequencycalibration',
            name='volt_uuc_setting_5',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='UUC Setting 5'),
        ),
    ]
