# Generated by Django 5.2.4 on 2025-09-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibrate', '0027_highfrequencycalibration_freq_measured_value_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lowfrequencycalibration',
            name='ac_error',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Error (AC)'),
        ),
        migrations.AddField(
            model_name='lowfrequencycalibration',
            name='ac_pass_fail',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Pass/Fail (AC)'),
        ),
        migrations.AddField(
            model_name='lowfrequencycalibration',
            name='ac_remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Remarks (AC)'),
        ),
        migrations.AddField(
            model_name='lowfrequencycalibration',
            name='dc_error',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Error (DC)'),
        ),
        migrations.AddField(
            model_name='lowfrequencycalibration',
            name='dc_pass_fail',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Pass/Fail (DC)'),
        ),
        migrations.AddField(
            model_name='lowfrequencycalibration',
            name='dc_remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Remarks (DC)'),
        ),
        migrations.AddField(
            model_name='lowfrequencycalibration',
            name='res_error',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Error (Resistance)'),
        ),
        migrations.AddField(
            model_name='lowfrequencycalibration',
            name='res_pass_fail',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Pass/Fail (Resistance)'),
        ),
        migrations.AddField(
            model_name='lowfrequencycalibration',
            name='res_remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Remarks (Resistance)'),
        ),
    ]
