# Generated by Django 5.2.4 on 2025-09-25 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calibrate', '0028_lowfrequencycalibration_ac_error_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CalibrationForce',
        ),
    ]
