# Generated by Django 5.2.4 on 2025-09-25 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibrate', '0029_remove_force_gauge'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calibrationpressure',
            options={'verbose_name': 'ข้อมูลสอบเทียบ Pressure', 'verbose_name_plural': 'ข้อมูลสอบเทียบ Pressure'},
        ),
        migrations.AddField(
            model_name='calibrationpressure',
            name='measurement_range',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ช่วงการวัด'),
        ),
        migrations.AlterField(
            model_name='calibrationpressure',
            name='cal_pressure_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='รหัสการสอบเทียบ Pressure'),
        ),
    ]
