# Generated by Django 5.2.4 on 2025-09-26 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibrate', '0030_add_measurement_range_to_pressure'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calibrationtorque',
            options={'verbose_name': 'ข้อมูลสอบเทียบ Torque', 'verbose_name_plural': 'ข้อมูลสอบเทียบ Torque'},
        ),
        migrations.AddField(
            model_name='calibrationtorque',
            name='ccw_actual',
            field=models.FloatField(blank=True, null=True, verbose_name='ค่าจริง CCW'),
        ),
        migrations.AddField(
            model_name='calibrationtorque',
            name='cw_actual',
            field=models.FloatField(blank=True, null=True, verbose_name='ค่าจริง CW'),
        ),
        migrations.AlterField(
            model_name='calibrationtorque',
            name='cal_torque_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='รหัสการสอบเทียบ Torque'),
        ),
    ]
