# Generated by Django 5.2.4 on 2025-09-26 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibrate', '0031_add_actual_fields_to_torque'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibrationtorque',
            name='ccw_actual_2',
            field=models.FloatField(blank=True, null=True, verbose_name='ค่าจริง CCW 2'),
        ),
        migrations.AddField(
            model_name='calibrationtorque',
            name='ccw_actual_3',
            field=models.FloatField(blank=True, null=True, verbose_name='ค่าจริง CCW 3'),
        ),
        migrations.AddField(
            model_name='calibrationtorque',
            name='ccw_error_2',
            field=models.FloatField(blank=True, null=True, verbose_name='ค่าความคลาดเคลื่อน CCW 2'),
        ),
        migrations.AddField(
            model_name='calibrationtorque',
            name='ccw_error_3',
            field=models.FloatField(blank=True, null=True, verbose_name='ค่าความคลาดเคลื่อน CCW 3'),
        ),
        migrations.AddField(
            model_name='calibrationtorque',
            name='ccw_tolerance_end_2',
            field=models.FloatField(blank=True, null=True, verbose_name='ค่าความคลาดเคลื่อนสิ้นสุด CCW 2'),
        ),
        migrations.AddField(
            model_name='calibrationtorque',
            name='ccw_tolerance_end_3',
            field=models.FloatField(blank=True, null=True, verbose_name='ค่าความคลาดเคลื่อนสิ้นสุด CCW 3'),
        ),
        migrations.AddField(
            model_name='calibrationtorque',
            name='ccw_tolerance_start_2',
            field=models.FloatField(blank=True, null=True, verbose_name='ค่าความคลาดเคลื่อนเริ่มต้น CCW 2'),
        ),
        migrations.AddField(
            model_name='calibrationtorque',
            name='ccw_tolerance_start_3',
            field=models.FloatField(blank=True, null=True, verbose_name='ค่าความคลาดเคลื่อนเริ่มต้น CCW 3'),
        ),
        migrations.AddField(
            model_name='calibrationtorque',
            name='ccwset_2',
            field=models.FloatField(blank=True, null=True, verbose_name='ตั้งค่า CCW 2'),
        ),
        migrations.AddField(
            model_name='calibrationtorque',
            name='ccwset_3',
            field=models.FloatField(blank=True, null=True, verbose_name='ตั้งค่า CCW 3'),
        ),
        migrations.AddField(
            model_name='calibrationtorque',
            name='cw_actual_2',
            field=models.FloatField(blank=True, null=True, verbose_name='ค่าจริง CW 2'),
        ),
        migrations.AddField(
            model_name='calibrationtorque',
            name='cw_actual_3',
            field=models.FloatField(blank=True, null=True, verbose_name='ค่าจริง CW 3'),
        ),
        migrations.AddField(
            model_name='calibrationtorque',
            name='cw_error_2',
            field=models.FloatField(blank=True, null=True, verbose_name='ค่าความคลาดเคลื่อน CW 2'),
        ),
        migrations.AddField(
            model_name='calibrationtorque',
            name='cw_error_3',
            field=models.FloatField(blank=True, null=True, verbose_name='ค่าความคลาดเคลื่อน CW 3'),
        ),
        migrations.AddField(
            model_name='calibrationtorque',
            name='cw_tolerance_end_2',
            field=models.FloatField(blank=True, null=True, verbose_name='ค่าความคลาดเคลื่อนสิ้นสุด CW 2'),
        ),
        migrations.AddField(
            model_name='calibrationtorque',
            name='cw_tolerance_end_3',
            field=models.FloatField(blank=True, null=True, verbose_name='ค่าความคลาดเคลื่อนสิ้นสุด CW 3'),
        ),
        migrations.AddField(
            model_name='calibrationtorque',
            name='cw_tolerance_start_2',
            field=models.FloatField(blank=True, null=True, verbose_name='ค่าความคลาดเคลื่อนเริ่มต้น CW 2'),
        ),
        migrations.AddField(
            model_name='calibrationtorque',
            name='cw_tolerance_start_3',
            field=models.FloatField(blank=True, null=True, verbose_name='ค่าความคลาดเคลื่อนเริ่มต้น CW 3'),
        ),
        migrations.AddField(
            model_name='calibrationtorque',
            name='cwset_2',
            field=models.FloatField(blank=True, null=True, verbose_name='ตั้งค่า CW 2'),
        ),
        migrations.AddField(
            model_name='calibrationtorque',
            name='cwset_3',
            field=models.FloatField(blank=True, null=True, verbose_name='ตั้งค่า CW 3'),
        ),
    ]
