# Generated by Django 5.2.4 on 2025-09-26 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibrate', '0032_add_additional_torque_rows'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibrationtorque',
            name='measurement_range',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ช่วงการวัด'),
        ),
        migrations.AddField(
            model_name='dialgaugecalibration',
            name='measurement_range',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ช่วงการวัด'),
        ),
    ]
