# Generated by Django 5.2.4 on 2025-09-26 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibrate', '0033_calibrationtorque_measurement_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibrationpressure',
            name='actual',
            field=models.FloatField(blank=True, null=True, verbose_name='ค่าจริง'),
        ),
    ]
