# Generated by Django 5.2.4 on 2025-09-26 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibrate', '0034_add_actual_field_to_pressure'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibrationpressure',
            name='actual_2',
            field=models.FloatField(blank=True, null=True, verbose_name='ค่าจริง (แถว 2)'),
        ),
        migrations.AddField(
            model_name='calibrationpressure',
            name='actual_3',
            field=models.FloatField(blank=True, null=True, verbose_name='ค่าจริง (แถว 3)'),
        ),
        migrations.AddField(
            model_name='calibrationpressure',
            name='actual_4',
            field=models.FloatField(blank=True, null=True, verbose_name='ค่าจริง (แถว 4)'),
        ),
        migrations.AddField(
            model_name='calibrationpressure',
            name='actual_5',
            field=models.FloatField(blank=True, null=True, verbose_name='ค่าจริง (แถว 5)'),
        ),
        migrations.AddField(
            model_name='calibrationpressure',
            name='actual_6',
            field=models.FloatField(blank=True, null=True, verbose_name='ค่าจริง (แถว 6)'),
        ),
    ]
