# Generated by Django 5.2.4 on 2025-09-26 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibrate', '0035_add_actual_fields_to_pressure_rows'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibrationpressure',
            name='tolerance_end_2',
            field=models.FloatField(blank=True, null=True, verbose_name='ค่าความคลาดเคลื่อนสิ้นสุด (แถว 2)'),
        ),
        migrations.AddField(
            model_name='calibrationpressure',
            name='tolerance_end_3',
            field=models.FloatField(blank=True, null=True, verbose_name='ค่าความคลาดเคลื่อนสิ้นสุด (แถว 3)'),
        ),
        migrations.AddField(
            model_name='calibrationpressure',
            name='tolerance_end_4',
            field=models.FloatField(blank=True, null=True, verbose_name='ค่าความคลาดเคลื่อนสิ้นสุด (แถว 4)'),
        ),
        migrations.AddField(
            model_name='calibrationpressure',
            name='tolerance_end_5',
            field=models.FloatField(blank=True, null=True, verbose_name='ค่าความคลาดเคลื่อนสิ้นสุด (แถว 5)'),
        ),
        migrations.AddField(
            model_name='calibrationpressure',
            name='tolerance_end_6',
            field=models.FloatField(blank=True, null=True, verbose_name='ค่าความคลาดเคลื่อนสิ้นสุด (แถว 6)'),
        ),
        migrations.AddField(
            model_name='calibrationpressure',
            name='tolerance_start_2',
            field=models.FloatField(blank=True, null=True, verbose_name='ค่าความคลาดเคลื่อนเริ่มต้น (แถว 2)'),
        ),
        migrations.AddField(
            model_name='calibrationpressure',
            name='tolerance_start_3',
            field=models.FloatField(blank=True, null=True, verbose_name='ค่าความคลาดเคลื่อนเริ่มต้น (แถว 3)'),
        ),
        migrations.AddField(
            model_name='calibrationpressure',
            name='tolerance_start_4',
            field=models.FloatField(blank=True, null=True, verbose_name='ค่าความคลาดเคลื่อนเริ่มต้น (แถว 4)'),
        ),
        migrations.AddField(
            model_name='calibrationpressure',
            name='tolerance_start_5',
            field=models.FloatField(blank=True, null=True, verbose_name='ค่าความคลาดเคลื่อนเริ่มต้น (แถว 5)'),
        ),
        migrations.AddField(
            model_name='calibrationpressure',
            name='tolerance_start_6',
            field=models.FloatField(blank=True, null=True, verbose_name='ค่าความคลาดเคลื่อนเริ่มต้น (แถว 6)'),
        ),
    ]
