# Generated by Django 5.2.4 on 2025-09-26 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibrate', '0036_add_tolerance_fields_to_pressure_rows'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balancecalibration',
            name='linear_tolerance_limit',
        ),
        migrations.AddField(
            model_name='balancecalibration',
            name='linear_conventional_mass_2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Conventional Mass (g) - Row 2'),
        ),
        migrations.AddField(
            model_name='balancecalibration',
            name='linear_conventional_mass_3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Conventional Mass (g) - Row 3'),
        ),
        migrations.AddField(
            model_name='balancecalibration',
            name='linear_conventional_mass_4',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Conventional Mass (g) - Row 4'),
        ),
        migrations.AddField(
            model_name='balancecalibration',
            name='linear_conventional_mass_5',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Conventional Mass (g) - Row 5'),
        ),
        migrations.AddField(
            model_name='balancecalibration',
            name='linear_displayed_value_2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Displayed Value (g) - Row 2'),
        ),
        migrations.AddField(
            model_name='balancecalibration',
            name='linear_displayed_value_3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Displayed Value (g) - Row 3'),
        ),
        migrations.AddField(
            model_name='balancecalibration',
            name='linear_displayed_value_4',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Displayed Value (g) - Row 4'),
        ),
        migrations.AddField(
            model_name='balancecalibration',
            name='linear_displayed_value_5',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Displayed Value (g) - Row 5'),
        ),
        migrations.AddField(
            model_name='balancecalibration',
            name='linear_error_2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Error (g) - Row 2'),
        ),
        migrations.AddField(
            model_name='balancecalibration',
            name='linear_error_3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Error (g) - Row 3'),
        ),
        migrations.AddField(
            model_name='balancecalibration',
            name='linear_error_4',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Error (g) - Row 4'),
        ),
        migrations.AddField(
            model_name='balancecalibration',
            name='linear_error_5',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Error (g) - Row 5'),
        ),
        migrations.AddField(
            model_name='balancecalibration',
            name='linear_nominal_value_2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nominal Value (g) - Row 2'),
        ),
        migrations.AddField(
            model_name='balancecalibration',
            name='linear_nominal_value_3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nominal Value (g) - Row 3'),
        ),
        migrations.AddField(
            model_name='balancecalibration',
            name='linear_nominal_value_4',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nominal Value (g) - Row 4'),
        ),
        migrations.AddField(
            model_name='balancecalibration',
            name='linear_nominal_value_5',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nominal Value (g) - Row 5'),
        ),
        migrations.AddField(
            model_name='balancecalibration',
            name='linear_uncertainty_2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Uncertainty (g) - Row 2'),
        ),
        migrations.AddField(
            model_name='balancecalibration',
            name='linear_uncertainty_3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Uncertainty (g) - Row 3'),
        ),
        migrations.AddField(
            model_name='balancecalibration',
            name='linear_uncertainty_4',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Uncertainty (g) - Row 4'),
        ),
        migrations.AddField(
            model_name='balancecalibration',
            name='linear_uncertainty_5',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Uncertainty (g) - Row 5'),
        ),
    ]
