# Generated by Django 5.2.4 on 2025-09-26 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibrate', '0037_add_linear_fields_to_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancecalibration',
            name='measurement_range',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ช่วงการวัด'),
        ),
    ]
