# Generated by Django 5.2.4 on 2025-09-26 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibrate', '0038_add_measurement_range_to_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialgaugecalibration',
            name='actual_2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Actual( inch ) - Row 2'),
        ),
        migrations.AddField(
            model_name='dialgaugecalibration',
            name='actual_3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Actual( inch ) - Row 3'),
        ),
        migrations.AddField(
            model_name='dialgaugecalibration',
            name='actual_4',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Actual( inch ) - Row 4'),
        ),
        migrations.AddField(
            model_name='dialgaugecalibration',
            name='actual_5',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Actual( inch ) - Row 5'),
        ),
        migrations.AddField(
            model_name='dialgaugecalibration',
            name='error_2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Error( inch ) - Row 2'),
        ),
        migrations.AddField(
            model_name='dialgaugecalibration',
            name='error_3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Error( inch ) - Row 3'),
        ),
        migrations.AddField(
            model_name='dialgaugecalibration',
            name='error_4',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Error( inch ) - Row 4'),
        ),
        migrations.AddField(
            model_name='dialgaugecalibration',
            name='error_5',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Error( inch ) - Row 5'),
        ),
        migrations.AddField(
            model_name='dialgaugecalibration',
            name='set_2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='UUC.Set( inch ) - Row 2'),
        ),
        migrations.AddField(
            model_name='dialgaugecalibration',
            name='set_3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='UUC.Set( inch ) - Row 3'),
        ),
        migrations.AddField(
            model_name='dialgaugecalibration',
            name='set_4',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='UUC.Set( inch ) - Row 4'),
        ),
        migrations.AddField(
            model_name='dialgaugecalibration',
            name='set_5',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='UUC.Set( inch ) - Row 5'),
        ),
        migrations.AddField(
            model_name='dialgaugecalibration',
            name='tolerance_limit_2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tolerance Limit - Row 2'),
        ),
        migrations.AddField(
            model_name='dialgaugecalibration',
            name='tolerance_limit_3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tolerance Limit - Row 3'),
        ),
        migrations.AddField(
            model_name='dialgaugecalibration',
            name='tolerance_limit_4',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tolerance Limit - Row 4'),
        ),
        migrations.AddField(
            model_name='dialgaugecalibration',
            name='tolerance_limit_5',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tolerance Limit - Row 5'),
        ),
    ]
