# Generated by Django 5.2.4 on 2025-09-26 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibrate', '0039_add_dial_gauge_table_rows'),
    ]

    operations = [
        migrations.AddField(
            model_name='highfrequencycalibration',
            name='measurement_range',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ช่วงการวัด'),
        ),
    ]
