# Generated by Django 5.2.4 on 2025-09-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibrate', '0040_add_measurement_range_to_high_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='lowfrequencycalibration',
            name='measurement_range',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ช่วงการวัด'),
        ),
    ]
