# Generated by Django 5.2.4 on 2025-09-26 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibrate', '0041_add_measurement_range_to_low_frequency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lowfrequencycalibration',
            name='ac_error',
        ),
        migrations.RemoveField(
            model_name='lowfrequencycalibration',
            name='ac_pass_fail',
        ),
        migrations.RemoveField(
            model_name='lowfrequencycalibration',
            name='ac_remarks',
        ),
        migrations.RemoveField(
            model_name='lowfrequencycalibration',
            name='dc_error',
        ),
        migrations.RemoveField(
            model_name='lowfrequencycalibration',
            name='dc_pass_fail',
        ),
        migrations.RemoveField(
            model_name='lowfrequencycalibration',
            name='dc_remarks',
        ),
        migrations.RemoveField(
            model_name='lowfrequencycalibration',
            name='res_error',
        ),
        migrations.RemoveField(
            model_name='lowfrequencycalibration',
            name='res_pass_fail',
        ),
        migrations.RemoveField(
            model_name='lowfrequencycalibration',
            name='res_remarks',
        ),
        migrations.AddField(
            model_name='lowfrequencycalibration',
            name='ac_measured_value_2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Measured Value (AC) 2'),
        ),
        migrations.AddField(
            model_name='lowfrequencycalibration',
            name='ac_measured_value_3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Measured Value (AC) 3'),
        ),
        migrations.AddField(
            model_name='lowfrequencycalibration',
            name='ac_measured_value_4',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Measured Value (AC) 4'),
        ),
        migrations.AddField(
            model_name='lowfrequencycalibration',
            name='ac_measured_value_5',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Measured Value (AC) 5'),
        ),
        migrations.AddField(
            model_name='lowfrequencycalibration',
            name='ac_tolerance_limit_2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tolerance Limit (AC) 2'),
        ),
        migrations.AddField(
            model_name='lowfrequencycalibration',
            name='ac_tolerance_limit_3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tolerance Limit (AC) 3'),
        ),
        migrations.AddField(
            model_name='lowfrequencycalibration',
            name='ac_tolerance_limit_4',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tolerance Limit (AC) 4'),
        ),
        migrations.AddField(
            model_name='lowfrequencycalibration',
            name='ac_tolerance_limit_5',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tolerance Limit (AC) 5'),
        ),
        migrations.AddField(
            model_name='lowfrequencycalibration',
            name='ac_uncertainty_2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Uncertainty (±) (AC) 2'),
        ),
        migrations.AddField(
            model_name='lowfrequencycalibration',
            name='ac_uncertainty_3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Uncertainty (±) (AC) 3'),
        ),
        migrations.AddField(
            model_name='lowfrequencycalibration',
            name='ac_uncertainty_4',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Uncertainty (±) (AC) 4'),
        ),
        migrations.AddField(
            model_name='lowfrequencycalibration',
            name='ac_uncertainty_5',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Uncertainty (±) (AC) 5'),
        ),
        migrations.AddField(
            model_name='lowfrequencycalibration',
            name='ac_uuc_range_2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='UUC Range (AC) 2'),
        ),
        migrations.AddField(
            model_name='lowfrequencycalibration',
            name='ac_uuc_range_3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='UUC Range (AC) 3'),
        ),
        migrations.AddField(
            model_name='lowfrequencycalibration',
            name='ac_uuc_range_4',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='UUC Range (AC) 4'),
        ),
        migrations.AddField(
            model_name='lowfrequencycalibration',
            name='ac_uuc_range_5',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='UUC Range (AC) 5'),
        ),
        migrations.AddField(
            model_name='lowfrequencycalibration',
            name='ac_uuc_setting_2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='UUC Setting (AC) 2'),
        ),
        migrations.AddField(
            model_name='lowfrequencycalibration',
            name='ac_uuc_setting_3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='UUC Setting (AC) 3'),
        ),
        migrations.AddField(
            model_name='lowfrequencycalibration',
            name='ac_uuc_setting_4',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='UUC Setting (AC) 4'),
        ),
        migrations.AddField(
            model_name='lowfrequencycalibration',
            name='ac_uuc_setting_5',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='UUC Setting (AC) 5'),
        ),
        migrations.AddField(
            model_name='lowfrequencycalibration',
            name='dc_measured_value_2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Measured Value (DC) 2'),
        ),
        migrations.AddField(
            model_name='lowfrequencycalibration',
            name='dc_measured_value_3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Measured Value (DC) 3'),
        ),
        migrations.AddField(
            model_name='lowfrequencycalibration',
            name='dc_measured_value_4',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Measured Value (DC) 4'),
        ),
        migrations.AddField(
            model_name='lowfrequencycalibration',
            name='dc_measured_value_5',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Measured Value (DC) 5'),
        ),
        migrations.AddField(
            model_name='lowfrequencycalibration',
            name='dc_tolerance_limit_2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tolerance Limit (DC) 2'),
        ),
        migrations.AddField(
            model_name='lowfrequencycalibration',
            name='dc_tolerance_limit_3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tolerance Limit (DC) 3'),
        ),
        migrations.AddField(
            model_name='lowfrequencycalibration',
            name='dc_tolerance_limit_4',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tolerance Limit (DC) 4'),
        ),
        migrations.AddField(
            model_name='lowfrequencycalibration',
            name='dc_tolerance_limit_5',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tolerance Limit (DC) 5'),
        ),
        migrations.AddField(
            model_name='lowfrequencycalibration',
            name='dc_uncertainty_2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Uncertainty (±) (DC) 2'),
        ),
        migrations.AddField(
            model_name='lowfrequencycalibration',
            name='dc_uncertainty_3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Uncertainty (±) (DC) 3'),
        ),
        migrations.AddField(
            model_name='lowfrequencycalibration',
            name='dc_uncertainty_4',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Uncertainty (±) (DC) 4'),
        ),
        migrations.AddField(
            model_name='lowfrequencycalibration',
            name='dc_uncertainty_5',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Uncertainty (±) (DC) 5'),
        ),
        migrations.AddField(
            model_name='lowfrequencycalibration',
            name='dc_uuc_range_2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='UUC Range (DC) 2'),
        ),
        migrations.AddField(
            model_name='lowfrequencycalibration',
            name='dc_uuc_range_3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='UUC Range (DC) 3'),
        ),
        migrations.AddField(
            model_name='lowfrequencycalibration',
            name='dc_uuc_range_4',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='UUC Range (DC) 4'),
        ),
        migrations.AddField(
            model_name='lowfrequencycalibration',
            name='dc_uuc_range_5',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='UUC Range (DC) 5'),
        ),
        migrations.AddField(
            model_name='lowfrequencycalibration',
            name='dc_uuc_setting_2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='UUC Setting (DC) 2'),
        ),
        migrations.AddField(
            model_name='lowfrequencycalibration',
            name='dc_uuc_setting_3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='UUC Setting (DC) 3'),
        ),
        migrations.AddField(
            model_name='lowfrequencycalibration',
            name='dc_uuc_setting_4',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='UUC Setting (DC) 4'),
        ),
        migrations.AddField(
            model_name='lowfrequencycalibration',
            name='dc_uuc_setting_5',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='UUC Setting (DC) 5'),
        ),
        migrations.AddField(
            model_name='lowfrequencycalibration',
            name='res_measured_value_2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Measured Value (Resistance) 2'),
        ),
        migrations.AddField(
            model_name='lowfrequencycalibration',
            name='res_measured_value_3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Measured Value (Resistance) 3'),
        ),
        migrations.AddField(
            model_name='lowfrequencycalibration',
            name='res_measured_value_4',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Measured Value (Resistance) 4'),
        ),
        migrations.AddField(
            model_name='lowfrequencycalibration',
            name='res_measured_value_5',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Measured Value (Resistance) 5'),
        ),
        migrations.AddField(
            model_name='lowfrequencycalibration',
            name='res_tolerance_limit_2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tolerance Limit (Resistance) 2'),
        ),
        migrations.AddField(
            model_name='lowfrequencycalibration',
            name='res_tolerance_limit_3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tolerance Limit (Resistance) 3'),
        ),
        migrations.AddField(
            model_name='lowfrequencycalibration',
            name='res_tolerance_limit_4',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tolerance Limit (Resistance) 4'),
        ),
        migrations.AddField(
            model_name='lowfrequencycalibration',
            name='res_tolerance_limit_5',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tolerance Limit (Resistance) 5'),
        ),
        migrations.AddField(
            model_name='lowfrequencycalibration',
            name='res_uncertainty_2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Uncertainty (±) (Resistance) 2'),
        ),
        migrations.AddField(
            model_name='lowfrequencycalibration',
            name='res_uncertainty_3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Uncertainty (±) (Resistance) 3'),
        ),
        migrations.AddField(
            model_name='lowfrequencycalibration',
            name='res_uncertainty_4',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Uncertainty (±) (Resistance) 4'),
        ),
        migrations.AddField(
            model_name='lowfrequencycalibration',
            name='res_uncertainty_5',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Uncertainty (±) (Resistance) 5'),
        ),
        migrations.AddField(
            model_name='lowfrequencycalibration',
            name='res_uuc_range_2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='UUC Range (Resistance) 2'),
        ),
        migrations.AddField(
            model_name='lowfrequencycalibration',
            name='res_uuc_range_3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='UUC Range (Resistance) 3'),
        ),
        migrations.AddField(
            model_name='lowfrequencycalibration',
            name='res_uuc_range_4',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='UUC Range (Resistance) 4'),
        ),
        migrations.AddField(
            model_name='lowfrequencycalibration',
            name='res_uuc_range_5',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='UUC Range (Resistance) 5'),
        ),
        migrations.AddField(
            model_name='lowfrequencycalibration',
            name='res_uuc_setting_2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='UUC Setting (Resistance) 2'),
        ),
        migrations.AddField(
            model_name='lowfrequencycalibration',
            name='res_uuc_setting_3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='UUC Setting (Resistance) 3'),
        ),
        migrations.AddField(
            model_name='lowfrequencycalibration',
            name='res_uuc_setting_4',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='UUC Setting (Resistance) 4'),
        ),
        migrations.AddField(
            model_name='lowfrequencycalibration',
            name='res_uuc_setting_5',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='UUC Setting (Resistance) 5'),
        ),
    ]
