# Generated by Django 5.2.4 on 2025-09-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibrate', '0042_add_low_frequency_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='microwavecalibration',
            name='dc_measured_value_2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Measured Value (DC) 2'),
        ),
        migrations.AddField(
            model_name='microwavecalibration',
            name='dc_measured_value_3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Measured Value (DC) 3'),
        ),
        migrations.AddField(
            model_name='microwavecalibration',
            name='dc_measured_value_4',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Measured Value (DC) 4'),
        ),
        migrations.AddField(
            model_name='microwavecalibration',
            name='dc_measured_value_5',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Measured Value (DC) 5'),
        ),
        migrations.AddField(
            model_name='microwavecalibration',
            name='dc_tolerance_limit_2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tolerance Limit (DC) 2'),
        ),
        migrations.AddField(
            model_name='microwavecalibration',
            name='dc_tolerance_limit_3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tolerance Limit (DC) 3'),
        ),
        migrations.AddField(
            model_name='microwavecalibration',
            name='dc_tolerance_limit_4',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tolerance Limit (DC) 4'),
        ),
        migrations.AddField(
            model_name='microwavecalibration',
            name='dc_tolerance_limit_5',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tolerance Limit (DC) 5'),
        ),
        migrations.AddField(
            model_name='microwavecalibration',
            name='dc_uncertainty_2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Uncertainty (±) (DC) 2'),
        ),
        migrations.AddField(
            model_name='microwavecalibration',
            name='dc_uncertainty_3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Uncertainty (±) (DC) 3'),
        ),
        migrations.AddField(
            model_name='microwavecalibration',
            name='dc_uncertainty_4',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Uncertainty (±) (DC) 4'),
        ),
        migrations.AddField(
            model_name='microwavecalibration',
            name='dc_uncertainty_5',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Uncertainty (±) (DC) 5'),
        ),
        migrations.AddField(
            model_name='microwavecalibration',
            name='dc_uuc_range_2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='UUC Range (DC) 2'),
        ),
        migrations.AddField(
            model_name='microwavecalibration',
            name='dc_uuc_range_3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='UUC Range (DC) 3'),
        ),
        migrations.AddField(
            model_name='microwavecalibration',
            name='dc_uuc_range_4',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='UUC Range (DC) 4'),
        ),
        migrations.AddField(
            model_name='microwavecalibration',
            name='dc_uuc_range_5',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='UUC Range (DC) 5'),
        ),
        migrations.AddField(
            model_name='microwavecalibration',
            name='dc_uuc_setting_2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='UUC Setting (DC) 2'),
        ),
        migrations.AddField(
            model_name='microwavecalibration',
            name='dc_uuc_setting_3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='UUC Setting (DC) 3'),
        ),
        migrations.AddField(
            model_name='microwavecalibration',
            name='dc_uuc_setting_4',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='UUC Setting (DC) 4'),
        ),
        migrations.AddField(
            model_name='microwavecalibration',
            name='dc_uuc_setting_5',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='UUC Setting (DC) 5'),
        ),
    ]
