# Generated by Django 5.2.4 on 2025-09-29 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibrate', '0043_microwavecalibration_dc_measured_value_2_and_more'),
        ('machine', '0007_machine_customer_asset_id_machine_option'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalibrationEquipmentUsed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calibration_type', models.CharField(max_length=50, verbose_name='ประเภทการสอบเทียบ')),
                ('calibration_id', models.PositiveIntegerField(verbose_name='รหัสการสอบเทียบ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine.calibrationequipment', verbose_name='เครื่องมือที่ใช้สอบเทียบ')),
            ],
            options={
                'verbose_name': 'เครื่องมือที่ใช้ในการสอบเทียบ',
                'verbose_name_plural': 'เครื่องมือที่ใช้ในการสอบเทียบ',
                'unique_together': {('calibration_type', 'calibration_id', 'equipment')},
            },
        ),
    ]
