# Generated by Django 5.2.4 on 2025-10-03 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibrate', '0044_calibrationequipmentused'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialgaugecalibration',
            name='certificate_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='หมายเลขใบรับรอง'),
        ),
    ]
