# Generated by Django 5.2.4 on 2025-10-03 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calibrate', '0010_update_torque_default_status'),
        ('calibrate', '0045_dialgaugecalibration_certificate_number'),
    ]

    operations = [
    ]
